### PR TITLE
[grid] rework the retry of http requests #14917

### LINKED ISSUE #14917: [🐛 Bug]: serverErrorPolicy does retry on `Exception` / `Error`
### What happened?

The `serverErrorPolicy` inside the `org.openqa.selenium.remote.http.RetryRequest` does not only handle the server errors.
It basically handles all `Exception`s / `Error`s, i guess this is due tue a missunderstanding of the API of the library used here.
This increases the retries on `ConnectException` to 5, instead of only 3.

In general i think the use of this library is problematic, due to:
- A miss match between the naming of method / things inside the javadoc and what is actually happening (this is also the reason for this issue...).
   e.g. `ExecutionAttemptedEvent.getLastException` does return a `Throwable`, so we have a potential class cast exception in https://github.com/SeleniumHQ/selenium/blob/825b0406e0842992e4dd37c06b2dc9bafa27a37c/java/src/org/openqa/selenium/remote/http/RetryRequest.java#L87
   e.g. the javadoc of `RetryPolicy.handleIf` speaks about "exception" but meant is "throwable"
- It implies handling failues is super easy, just put it inside a retry and don't think about it.
  This will probably lead to leaks, e.g. leaking `sub` in case `pub` failes in https://github.com/SeleniumHQ/selenium/blob/825b0406e0842992e4dd37c06b2dc9bafa27a37c/java/src/org/openqa/selenium/events/zeromq/UnboundZmqEventBus.java#L134-L145
- I have debugged into to the code and it makes things complex compared to a simple loop. And complexity does bring bugs with it e.g. before PR #12838 the responses of concurrent failed request could get mixed.
- No response to most issues raised in the issue tracker, including one related to selenium https://github.com/failsafe-lib/failsafe/issues/386

So i would like to ask: Glue some patches on the code and hope the code does what it should or remove the library with a custom implementation aka. a simple loop?

### How can we reproduce the issue?

```shell
Run `RetryRequestTest.canThrowUnexpectedException` in debug mode to see the unexpected retries in the logs.

Or run the code below to see the 5 retries instead of 3.
HttpHandler handler =
        new RetryRequest()
            .andFinally(
                (HttpRequest request) -> {
                  throw new WebDriverException("oops", new ConnectException("Testing"));
                });
```

### Relevant log output

```shell
Dez. 19, 2024 11:50:53 AM org.openqa.selenium.remote.http.RetryRequest lambda$static$4
INFORMATION: Failure due to server error #1. Retrying.
Dez. 19, 2024 11:50:56 AM org.openqa.selenium.remote.http.RetryRequest lambda$static$4
INFORMATION: Failure due to server error #2. Retrying.
```

### Operating System

Win 10 x64

### Selenium version

4.27.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by joerg1985**
### Description
Remove the use of `dev.failsafe` inside the `RetryRequest` with a simple loop.

There is also a functional change, `Exception`s and error responses are delivered unmodified to the caller.
This will allow the caller to handle the original `Exception` / error response, so we do not loose data here.
The old mapping did also not return a valid W3C response, so the client should not have been able to decode it.

### Motivation and Context
see #14917

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Replaced the `dev.failsafe` library with a custom retry implementation using a simple loop mechanism
- Changed error handling behavior to preserve original exceptions and error responses instead of wrapping them
- Implemented configurable retry attempts:
  * Up to 3 retries for connection exceptions
  * Up to 2 retries for server errors
- Added comprehensive test coverage for the new implementation
- Removed external dependency on `dev.failsafe` library
- Improved logging of retry attempts with detailed error information

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>RetryRequest.java</strong><dd><code>Refactor HTTP request retry mechanism with custom implementation</code></dd></summary>
<hr>

java/src/org/openqa/selenium/remote/http/RetryRequest.java

<li>Replaced <code>dev.failsafe</code> library with a simple retry loop implementation<br> <li> Modified error handling to return original exceptions and error <br>responses<br> <li> Implemented configurable retry attempts for connection and server <br>errors<br> <li> Added detailed logging for retry attempts<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14924/files#diff-7f5ed1fae9402073cf64bccd57826c564147c32fc4a40641751c7a8172b78264">+34/-69</a>&nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>RetryRequestTest.java</strong><dd><code>Expand test coverage for RetryRequest implementation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/test/org/openqa/selenium/remote/http/RetryRequestTest.java

<li>Added new test cases for unexpected exceptions and retry behavior<br> <li> Enhanced multi-threaded test with increased iterations<br> <li> Added tests for connection failures and server error handling<br> <li> Updated assertions to match new error handling behavior<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14924/files#diff-5abfd7e20f534b71aa154f57701a2faa69b29ad636f6929db1ac8457b7fc5101">+90/-12</a>&nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>BUILD.bazel</strong><dd><code>Remove failsafe dependency from build configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/remote/http/BUILD.bazel

- Removed dependency on `dev.failsafe` library

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14924/files#diff-18f57661561345a8c506f313ad34af2f5c1e93b429ac87d96f4eb223fa7ad4ea">+0/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

File: java/src/org/openqa/selenium/remote/http/RetryRequest.java [hunk 1]
```diff
@@ -17,89 +17,55 @@
...
+          continue;
+        }
+
+        return response;
       }
-    }
-    return executionAttemptedEvent.getLastResult();
+
+      throw new IllegalStateException(
+          "Effective unreachable code reached, please raise a bug ticket.");
```
Comment (diemol) [inline java/src/org/openqa/selenium/remote/http/RetryRequest.java]: I would summarize here the failure; I am not sure if telling the user to raise a ticket will help them with the issue as, in theory, the issue comes from a network failure in their environment.

File: java/src/org/openqa/selenium/remote/http/RetryRequest.java [hunk 2]
```diff
@@ -17,89 +17,55 @@
...
 
   @Override
   public HttpHandler apply(HttpHandler next) {
-    return req ->
-        Failsafe.with(fallback)
-            .compose(serverErrorPolicy)
-            .compose(connectionFailurePolicy)
-            .get(() -> next.execute(req));
-  }
+    return req -> {
```
Comment (diemol) [inline java/src/org/openqa/selenium/remote/http/RetryRequest.java:40]: Adding some code comments along the flow will help others understand what is being done, as the logic behind the code is not trivial.

**Review by diemol — CHANGES_REQUESTED** [review]
Just a couple of comments, but this looks very close to what I had in mind when you raised the ticket.

File: java/src/org/openqa/selenium/remote/http/RetryRequest.java (hunk 1 above)
Comment (joerg1985) [reply java/src/org/openqa/selenium/remote/http/RetryRequest.java]: This line is only reachable in case somebody does change the `static final int` values at the top of the class to inconsistent values, e.g. more retries than total attemps. So this is not related to any local networking issue.

I could replace this with an `AssertionError` to show this is a state we should never ever reach?

Comment (diemol) [reply java/src/org/openqa/selenium/remote/http/RetryRequest.java]: Oh, I missed that. Then I would say that in the throw instead of telling the user to raise a ticket.

**Comment by joerg1985** [comment]
@diemol i have updated the PR with some inline comments.

**Review by diemol — APPROVED** [review]
Thank you, @joerg1985!
