### PR TITLE
[grid] Improvement for Node handling

### LINKED ISSUE #13769: [🐛 Bug]: org.openqa.selenium.WebDriverException: Unable to route (POST) /session/0405a24bf1d06c6ae8402b8d12027934/...
### What happened?

When executing a command on a just timedout session a `WebDriverException: Unable to route ...` is raised.

### How can we reproduce the issue?

For some seconds after the session timedout there is a inconsistent state, until the `sessionCleanupNodeService` of the `LocalNode` did run. The `LocalSessionMap` still tells the session does exist, but the `Node.isSessionOwner` does return false. This will prevent the route inside the `Node` is matched and lead to the `WebDriverException: Unable to route ...`.

### Relevant log output

```shell
N/A
```

### Operating System

Win 10 x64

### Selenium version

4.17.1

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

### PR DESCRIPTION
**Pull request by VietND96**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Motivation and Context
checkSessionCount() - to check and drain node after sessions are reached. Steps in order, so in logs, we saw something like

> 09:51:06.344 INFO [LocalNode.checkSessionCount] - Draining Node, configured sessions value (1) has been reached.
09:51:06.533 INFO [LocalNode.newSession] - Session created by the Node. Id: b47edd11098edb876c805745161ea67c, Caps:

It might confuse that the session created in a draining node.
So, moving it to block finally { }
The trade-off is the session count will include both success and unsuccess. When the session comes, the remaining count decreases.
It could be suitable for autoscaling. For example, if a faulty Node (for unknown reasons), the session cannot be created, and the node will be drained to signal the scaler to scale a new one. Instead of keeping Node running, it biases the scaler already had enough nodes running.
Also, there was a request #13865 - Automatically drain node after n-failed session attempts. By moving that check to `finally` blocks, it would be best for both.

---
Add the `drain()` method to the shutdown hook. Node will send drain event to remove Node immediately once Runtime stopped.

---
Fixes #13769 - Exception `NoSuchSessionException` should throw out when command is routed to Node that session just timed out.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: java/src/org/openqa/selenium/grid/node/Node.java [hunk 1]
```diff
@@ -152,7 +152,10 @@ protected Node(
                     req ->
                         getSessionId(req.getUri())
                             .map(SessionId::new)
-                            .map(this::isSessionOwner)
+                            .map(
+                                sessionId ->
+                                    this.getSession(sessionId) != null
```
Comment (joerg1985) [inline java/src/org/openqa/selenium/grid/node/Node.java]: I do not understand this change here, it does not help match the route. The `this.getSession(sessionId)` should return null here, in case of #13769.
The `NodeTest.shouldOnlyRespondToWebDriverCommandsForSessionsTheNodeOwns` should fail, as soon as we enter here.

Comment (VietND96) [reply java/src/org/openqa/selenium/grid/node/Node.java]: I saw the test failure and updated something new, instead of testing against random UUID

File: java/src/org/openqa/selenium/grid/node/ForwardWebDriverCommand.java [hunk 2]
```diff
@@ -17,19 +17,30 @@
...
     this.node = Require.nonNull("Node", node);
   }
 
+  @Override
+  public boolean matches(HttpRequest req) {
+    return getSessionId(req.getUri())
+        .map(id -> node.isSessionOwner(new SessionId(id)))
+        .orElse(false);
+  }
+
```
Comment (joerg1985) [inline java/src/org/openqa/selenium/grid/node/ForwardWebDriverCommand.java]: Is this code reached? In my mind the the `isSessionOwner` must be checked inside the `execute` before calling  `node.executeWebDriverCommand`.

Comment (VietND96) [reply java/src/org/openqa/selenium/grid/node/ForwardWebDriverCommand.java]: You are correct! I updated and tried to check via a unit test. Can you review one more time

File: java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
+// Licensed to the Software Freedom Conservancy (SFC) under one
```
Comment (diemol) [inline java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java]: This test could go inside the `router` package. There are some others that do similar actions.

File: java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+import org.openqa.selenium.WebDriver;
+import org.openqa.selenium.chrome.ChromeOptions;
+import org.openqa.selenium.grid.Bootstrap;
+import org.openqa.selenium.remote.RemoteWebDriver;
+
+public class SessionTimeoutTest {
+  @Test
+  void testSessionTimeout() throws Exception {
+    Assumptions.assumeThat(System.getProperty("webdriver.chrome.binary")).isNull();
+    Bootstrap.main(("hub --host 127.0.0.1 --port 4444").split(" "));
```
Comment (diemol) [inline java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java]: Check other tests inside the `router` package, there are nicer ways to place the parameters.

File: java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+    Bootstrap.main(
+        ("node --host 127.0.0.1 --port 5555 --session-timeout 12 --selenium-manager true")
```
Comment (diemol) [inline java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java]: This test must be added to `.skipped-tests` because it cannot be executed in engflow. 

Or, find a way to set the driver, just like the `StressTest` does it.

**Review by diemol — CHANGES_REQUESTED** [review]

File: java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java (hunk 5 above)
Comment (VietND96) [reply java/test/org/openqa/selenium/grid/e2e/SessionTimeoutTest.java]: I moved test to `StressTest` and handle rely on current setup() in there

File: java/test/org/openqa/selenium/grid/router/StressTest.java [hunk 6]
```diff
@@ -124,4 +132,15 @@ void multipleSimultaneousSessions() throws Exception {
 
     CompletableFuture.allOf(futures).get(4, MINUTES);
   }
+
+  @Test
+  void testStopTimedOutSession() throws Exception {
+    assertThat(server.isStarted()).isTrue();
+    WebDriver driver =
```
Comment (diemol) [inline java/test/org/openqa/selenium/grid/router/StressTest.java]: Perhaps I am too picky, but this class has a specific purpose (Stress Test). To make sense, we either rename the class to something different or move the new test to its class.

**Review by diemol — CHANGES_REQUESTED** [review]

File: java/test/org/openqa/selenium/grid/router/StressTest.java (hunk 6 above)
Comment (VietND96) [reply java/test/org/openqa/selenium/grid/router/StressTest.java]: I updated it to `multipleSimultaneousSessionsTimedOut()`

**Review by diemol — APPROVED** [review]
