### PR TITLE
[java] Rescuing the remote cause for session creation errors

### LINKED ISSUE #16388: [🐛 Bug]:  [java] No proper error message misleading the user to analyze
### Description

**Error : Session is not created : Possible cause invalid address of the remote server or browser start up failed**
Please refer the appium java client issue and inturn it uses selenium  client
[https://github.com/appium/java-client/issues/2349](url) 

[  The problem is here.
when we are using Desired capabilities as option on Appium 3.0 server, it throws generic error session not created
as we know - Desired capabilities option is depreacted on 3.0
Expected : Its should throw Deprecated or unsupported desired capabilities or compile time error ]
------------------------------------------------------------------------------------------------

JAVA Version - 11/17/23

**Appium server - 3.0.2
Appium client - 10.0.0
**Selenium-java - 4.35.0**
IOS - XCUI test driver - 10.1.2
Testng- 7.5.1
Server URL : http://127.0.0.1:4723/
Even cross check with compatible matrix appium client & Selenium , Didnt helped me**

### Reproducible Code

```shell
// This sample code supports Appium Java client >=9
import org.testng.annotations.Test;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.ios.options.XCUITestOptions;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
public class NewTest2 {

	IOSDriver driver; 

	@BeforeClass
	public void setUp() {
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("acceptAlerts", true);
		capabilities.setCapability("trust", true);
		capabilities.setCapability("launchTimeout", 600000);
		capabilities.setCapability("newCommandTimeout", 600);
		capabilities.setCapability("automationName", "XCUITest");
	    capabilities.setCapability("app", "/Users/ga20055252/Downloads/uat-Runner.app");
		capabilities.setCapability("udid", "CB53FD24-EE7B-4EA8-BE4A-C3D88FA1AC1A");
		capabilities.setCapability("noReset", true);
		capabilities.setCapability("bundleId", "com.mgmresorts.enterprise.uat");
		capabilities.setCapability("wdaLaunchTimeout", 60000);
		capabilities.setCapability("autoDismissAlerts", true);
		capabilities.setCapability("fullReset", false);

		try {
			URL appiumServerUrl = new URL("http://127.0.0.1:4723/wd/hub");
			driver = new IOSDriver(appiumServerUrl, capabilities);
		} catch (MalformedURLException e) {	e.printStackTrace();}}

	@Test
	public void sampleTest() {
		try {Thread.sleep(3000);} catch (InterruptedException e) {e.printStackTrace();}
	}

	@AfterClass
	public void tearDown() {
		driver.quit();
	}
}
```

### Debugging Logs

```logs
Session is not created | No logs at all
```

### PR DESCRIPTION
**Pull request by diemol**
### 🔗 Related Issues
Fixes #16388

### 💥 What does this PR do?

Every now and then, someone complains because the real reason a remote session creation fails is hidden in the stack trace. This identifies the cause, if it exists, and displays it at the top level.

___

### **PR Type**
Bug fix

___

### **Description**
- Improved error messaging for remote session creation failures

- Extracts and displays the underlying cause message at the top level

- Prevents real error reasons from being hidden in stack traces

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["Session Creation Error"] --> B["Check for Cause"]
  B --> C["Extract Cause Message"]
  C --> D["Display at Top Level"]
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>RemoteWebDriver.java</strong><dd><code>Enhanced remote session error message extraction</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/remote/RemoteWebDriver.java

<ul><li>Enhanced error handling in <code>execute()</code> method for NEW_SESSION command<br> <li> Extracts cause message from exception chain when available<br> <li> Appends cause message to SessionNotCreatedException for better <br>visibility</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16418/files#diff-0cf141b01e48a733ec9037c51d8e610e7727d05a6b79aa0176def7c3a0fc311b">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: java/src/org/openqa/selenium/remote/RemoteWebDriver.java [hunk 1]
```diff
@@ -572,10 +572,14 @@ protected Response execute(CommandPayload payload) {
...
         } else {
+          // When this exception comes from a remote end, the real cause is usually hidden in the
+          // cause. Let's try to rescue it and display it at the top level.
+          String cause = e.getCause() != null ? e.getCause().getMessage() : "";
           toThrow =
               new SessionNotCreatedException(
                   "Possible causes are invalid address of the remote server or browser start-up"
-                      + " failure.",
+                      + " failure. "
+                      + cause,
```
Comment (valfirst) [inline java/src/org/openqa/selenium/remote/RemoteWebDriver.java]:
```suggestion
          String cause = e.getCause() != null ? " " + e.getCause().getMessage() : "";
toThrow =
new SessionNotCreatedException(
"Possible causes are invalid address of the remote server or browser start-up"
                      + " failure."
                      + cause,
```
?

Comment (diemol) [reply java/src/org/openqa/selenium/remote/RemoteWebDriver.java]: Wouldn't the text look strange without a space between phrases?

Comment (valfirst) [reply java/src/org/openqa/selenium/remote/RemoteWebDriver.java]: the space is added before the cause: `" " + e.getCause().getMessage()`

and if cause is not presented, then no extra space will be added

Comment (diemol) [reply java/src/org/openqa/selenium/remote/RemoteWebDriver.java]: I saw it on my phone. Now I get it. Thanks!

Comment (diemol) [reply java/src/org/openqa/selenium/remote/RemoteWebDriver.java]: Somehow it does not let me apply it here

imagen

Do you mind if I do it locally and push?

Comment (valfirst) [reply java/src/org/openqa/selenium/remote/RemoteWebDriver.java]: > Do you mind if I do it locally and push?

sure, no problem at all

Comment (diemol) [reply java/src/org/openqa/selenium/remote/RemoteWebDriver.java]: Thanks

**Review by titusfortner — APPROVED** [review]
