### PR TITLE
[java] Unify error message format for all Expected Conditions & add tests

### LINKED ISSUE #16005: [🚀 Feature]:  Better Logging and Debug Info for WebDriver Wait Failures
### Context  
Given that WebDriverWait` is heavily relied upon for synchronisation and a wait condition fails, the resulting `TimeoutException` often lacks sufficient context to understand what exactly went wrong. This slows down root cause analysis during triaging.

### Suggestion  
It would be helpful to enhance the exception message thrown by `WebDriverWait` when a condition times out. Specifically, include:
- The expected condition (via `.toString()`)
- The total timeout duration
- The locator (where applicable)

This added context can help quickly identify the exact point of failure without having to dig into logs or source code.

### Example  

**Current:**

Timed out waiting for condition.

**Proposed:**
Timed out after 10 seconds waiting for condition: visibility of element located by By.id("login")

### Why This Matters  
- This is a small, backward-compatible improvement with **high practical value**
- Helps quickly debug flaky or failing tests.

---

I’d be happy to raise a PR for this enhancement, if this sounds useful. 

### Have you considered any alternatives or workarounds?

_No response_

### LINKED ISSUE #16819: [🐛 Bug]: Some of ExpectedConditions do not wait for the condition
### Description

Selenium Java binding has a bunch of built-in checks: `ExpectedConditions`.
They are meant to _wait_ for some time until the desired condition is met.

I found that some of these conditions do not wait. Instead, they throw an exception right away. :(
This is clearly a bug.

### Reproducible Code

Given "waiter" with timeout 5 seconds

```java
FluentWait<WebDriver> wait = new FluentWait<>(driver)
  .withTimeout(ofSeconds(5))
```

 and an element that **appears after ~2 seconds**:
```html
  <div id="slow-cow" value="cow-123">Moooooooo</div>
```

These checks should wait for ~2 seconds and complete successfully:

```java
wait.until(presenceOfElementLocated(By.cssSelector("#slow-cow")));
wait.until(textToBePresentInElementLocated(slow, "Moooooooo"));
wait.until(textToBePresentInElementValue(slow, "cow-123"));
wait.until(elementToBeSelected(slow));
wait.until(elementSelectionStateToBe(slow, true));
wait.until(attributeToBe(slow, "value", "cow-123"));
wait.until(attributeContains(slow, "value", "cow-123"));
wait.until(presenceOfNestedElementLocatedBy(By.cssSelector("body"), slow));
wait.until(presenceOfNestedElementLocatedBy(driver.findElement(By.cssSelector("body")), slow));
wait.until(frameToBeAvailableAndSwitchToIt(By.id("slow-frame"))); // throws NoSuchElementException without waiting
```

But all they just throw immediately `NoSuchElementException` without any waiting. :(

### PR DESCRIPTION
**Pull request by asolntsev**
### **User description**
* Many of Expected Conditions generated misleading or incomplete error messages.
* Some didn't wait for the condition
* The error messages were not checked in tests at all. :(
* Timeout truncated the milliseconds part, showing "4 second(s)" instead of "4.5 seconds".

### 🔗 Related Issues
Fixes #16819
Fixes #16005  @ceekay10

### 🔄 Types of changes
- Cleanup (formatting, renaming)
- Bug fix (backwards compatible)

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Unified error message format across all Expected Conditions with consistent, informative messages

- Fixed timeout display to show decimal seconds (e.g., "4.5 seconds" instead of "4 second(s)")

- Enhanced error messages to include actual vs expected values and specific failure reasons

- Added comprehensive test coverage for error messages in Expected Conditions

- Improved exception handling to capture and report detailed error information

___

### Diagram Walkthrough

```mermaid
flowchart LR
  EC["Expected Conditions<br/>Error Messages"]
  EC -->|Unified Format| Format["Consistent Message<br/>Structure"]
  EC -->|Enhanced Info| Details["Actual vs Expected<br/>Values & Reasons"]
  EC -->|Better Timeout| Timeout["Decimal Seconds<br/>4.5s not 4s"]
  EC -->|Test Coverage| Tests["Error Message<br/>Assertions"]
```

<details><summary><h3>File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ExpectedConditions.java</strong><dd><code>Unified error messages and enhanced exception reporting</code>&nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/support/ui/ExpectedConditions.java

<ul><li>Refactored all Expected Condition error messages to follow unified <br>format with actual vs expected values<br> <li> Added exception tracking in conditions to capture and report specific <br>failure reasons<br> <li> Implemented <code>shortDescription()</code> helper method to format exception <br>messages consistently<br> <li> Enhanced conditions like <code>visibilityOfElementLocated</code>, <br><code>elementToBeClickable</code>, <code>textToBe</code> with detailed error context<br> <li> Fixed parameter naming for clarity (e.g., <code>text</code> → <code>expectedValue</code>, <br><code>frameLocator</code> → <code>frameIndex</code>)<br> <li> Improved exception handling to catch <code>NoSuchElementException</code> and <br><code>StaleElementReferenceException</code> separately<br> <li> Added logging for unexpected WebDriver exceptions</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16831/files#diff-9d144815e7045eabe45652340d3517cf24a5bc09c113f6f441aca18a3c0353a5">+541/-241</a></td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>FluentWait.java</strong><dd><code>Add human-readable timeout formatting with decimal seconds</code></dd></summary>
<hr>

java/src/org/openqa/selenium/support/ui/FluentWait.java

<ul><li>Implemented <code>formatTimeout()</code> static method to display durations in <br>human-readable format with decimal seconds<br> <li> Uses <code>BigDecimal</code> for precise millisecond-to-second conversion with <br>proper rounding<br> <li> Handles singular/plural forms ("1 second" vs "2 seconds")<br> <li> Updated timeout message format to use new <code>formatTimeout()</code> method<br> <li> Changed message layout to separate condition description from timeout <br>info with newline</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16831/files#diff-e33f54b8999af8e818a011f469e72eee95a3eb2b9bc69ffc5d496bb0da372838">+14/-3</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>WaitingConditions.java</strong><dd><code>Update test condition messages to unified format</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/test/org/openqa/selenium/WaitingConditions.java

<ul><li>Updated error message format in all test condition methods to match <br>unified style<br> <li> Enhanced <code>toString()</code> methods to include locator information and actual <br>vs expected values<br> <li> Improved <code>windowHandleCountToBe()</code> to track actual window handles and <br>provide detailed error messages<br> <li> Refactored lambda expressions to explicit <code>ExpectedCondition</code> <br>implementations for better error reporting</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16831/files#diff-7316b743189146f201933b51996505c7df3ca57cf0a2abb83055230c5634c3c2">+56/-23</a>&nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>FluentWaitTest.java</strong><dd><code>Add timeout formatting tests and update assertions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/test/org/openqa/selenium/support/ui/FluentWaitTest.java

<ul><li>Added new test <code>showsTimeoutInHumanReadableFormat()</code> to verify timeout <br>formatting with various durations<br> <li> Updated existing timeout message assertions to expect new format with <br>decimal seconds and newline separator<br> <li> Refactored mock initialization from <code>@BeforeEach</code> to field <br>initialization with <code>mock()</code><br> <li> Simplified import statements using wildcard imports</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16831/files#diff-4e24a343da46102baac872e657e69fb01b872b3845a7bfd9c1850b7e936e7b96">+32/-28</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>WaitingConditionsTest.java</strong><dd><code>Add error message assertion tests for waiting conditions</code>&nbsp; </dd></summary>
<hr>

java/test/org/openqa/selenium/WaitingConditionsTest.java

<ul><li>Added comprehensive error message tests for <code>elementTextToEqual()</code>, <br><code>elementTextToContain()</code>, <code>elementTextToMatch()</code><br> <li> Added error message tests for <code>pageSourceToContain()</code>, <br><code>elementLocationToBe()</code>, <code>windowHandleCountToBe()</code><br> <li> Each test verifies message format, timeout info, and build info <br>presence<br> <li> Tests validate that actual values are included in error messages</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16831/files#diff-a58e6d4196127bd8b34089d9782846a515afb2cc36671dab4c1dbdce23a50dd7">+87/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>FrameSwitchingTest.java</strong><dd><code>Add frame switching test with By locator</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/test/org/openqa/selenium/FrameSwitchingTest.java

<ul><li>Added new test <code>testShouldBeAbleToSwitchToFrameBySelector()</code> to verify <br>frame switching with <code>By</code> locator<br> <li> Test validates that frame can be switched using <br><code>frameToBeAvailableAndSwitchToIt(By)</code> method<br> <li> Tests frame deletion and re-addition scenarios</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16831/files#diff-6fba2941c93f873643bd14649d0525ec48b908f955f81a093b064ea60801ce6c">+18/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tbody></table>

</details>

___

### CODE REVIEW

File: java/src/org/openqa/selenium/support/ui/ExpectedConditions.java [hunk 1]
```diff
@@ -17,26 +17,23 @@
...
-import org.openqa.selenium.By;
-import org.openqa.selenium.JavascriptExecutor;
-import org.openqa.selenium.NoAlertPresentException;
-import org.openqa.selenium.NoSuchElementException;
-import org.openqa.selenium.NoSuchFrameException;
-import org.openqa.selenium.StaleElementReferenceException;
-import org.openqa.selenium.WebDriver;
-import org.openqa.selenium.WebDriverException;
-import org.openqa.selenium.WebElement;
+import org.openqa.selenium.*;
```
Comment (titusfortner) [inline java/src/org/openqa/selenium/support/ui/ExpectedConditions.java]: Does Selenide have a linter? Probably should figure out how to add `-Xep:WildcardImport:ERROR` to our format job

Comment (asolntsev) [reply java/src/org/openqa/selenium/support/ui/ExpectedConditions.java]: Yes, we use Checkstyle in Selenide, and "import *" is disabled with "AvoidStarImport" rule:
https://github.com/selenide/selenide/blob/5cd9d9cd47eabfb09f8d2d2c739ad1b4347e58b0/config/checkstyle/checkstyle.xml#L27

In this case, I recently re-created IDEA project - that's why my code style settings in IDEA have been reset to the default style. 

Fixed.
