### PR TITLE
[java] Add "se" prefixed capabilities to session response

### LINKED ISSUE #1431: [Firefox] Webdriver isn't work with 64 bit version of firefox
Single installation of firefox x64 returns an error for tests.
After start test run firefox instance (only for java) but after run return errors.

C#
```
Result StackTrace:	
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.Firefox.Internal.Executable.LocateFirefoxBinaryFromPlatform()
   at OpenQA.Selenium.Firefox.Internal.Executable..ctor(String userSpecifiedBinaryPath)
   at OpenQA.Selenium.Firefox.FirefoxBinary..ctor(String pathToFirefoxBinary)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor()
Result Message:	System.ComponentModel.Win32Exception : The system cannot find the file specified
```

Java
```
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
161268431903553903webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1451390671378,"updateDate":1451390671378,"applyBackgroundUpdates":1,"bootstrap":false,"size":3213569,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"45.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1451390671923	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"Zyi2si20fyvo","location":"app-global","version":"43.0.3","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1451359851119,"updateDate":1451359851119,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.3","maxVersion":"43.0.3"}],"targetPlatforms":[]}
1451390671923	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1451390671924	DeferredSave.extensions.json	DEBUG	Save changes
1451390671924	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1451390671924	addons.xpi-utils	DEBUG	Updating add-on states
1451390671925	addons.xpi-utils	DEBUG	Writing add-ons list
1451390671932	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1451390671933	addons.manager	DEBUG	Provider finished startup: XPIProvider
1451390671933	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1451390671933	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1451390671933	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1451390671933	addons.manager	DEBUG	Starting provider: GMPProvider
1451390671937	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1451390671938	addons.manager	DEBUG	Provider finished startup: GMPProvider
1451390671938	addons.manager	DEBUG	Starting provider: PluginProvider
1451390671938	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1451390671938	addons.manager	DEBUG	Provider finished startup: PluginProvider
1451390671938	addons.manager	DEBUG	Completed startup sequence
1451390672106	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1451390672106	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1451390672106	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1451390672154	DeferredSave.extensions.json	DEBUG	Starting write
1451390672287	addons.repository	DEBUG	No addons.json found.
1451390672287	DeferredSave.addons.json	DEBUG	Save changes
1451390672289	DeferredSave.addons.json	DEBUG	Starting timer
1451390672295	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1451390672296	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1451390672296	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1451390672299	DeferredSave.extensions.json	DEBUG	Write succeeded
1451390672299	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1451390672341	DeferredSave.addons.json	DEBUG	Starting write
1451390672372	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:123)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.epam.dailybeast.testtask.test.NewsPage.canOpenNewsPage(NewsPage.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
161268431903553903webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1451390671378,"updateDate":1451390671378,"applyBackgroundUpdates":1,"bootstrap":false,"size":3213569,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"45.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1451390671923	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"Zyi2si20fyvo","location":"app-global","version":"43.0.3","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1451359851119,"updateDate":1451359851119,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.3","maxVersion":"43.0.3"}],"targetPlatforms":[]}
1451390671923	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1451390671924	DeferredSave.extensions.json	DEBUG	Save changes
1451390671924	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1451390671924	addons.xpi-utils	DEBUG	Updating add-on states
1451390671925	addons.xpi-utils	DEBUG	Writing add-ons list
1451390671932	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1451390671933	addons.manager	DEBUG	Provider finished startup: XPIProvider
1451390671933	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1451390671933	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1451390671933	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1451390671933	addons.manager	DEBUG	Starting provider: GMPProvider
1451390671937	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1451390671938	addons.manager	DEBUG	Provider finished startup: GMPProvider
1451390671938	addons.manager	DEBUG	Starting provider: PluginProvider
1451390671938	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1451390671938	addons.manager	DEBUG	Provider finished startup: PluginProvider
1451390671938	addons.manager	DEBUG	Completed startup sequence
1451390672106	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1451390672106	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1451390672106	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1451390672154	DeferredSave.extensions.json	DEBUG	Starting write
1451390672287	addons.repository	DEBUG	No addons.json found.
1451390672287	DeferredSave.addons.json	DEBUG	Save changes
1451390672289	DeferredSave.addons.json	DEBUG	Starting timer
1451390672295	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1451390672296	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1451390672296	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1451390672299	DeferredSave.extensions.json	DEBUG	Write succeeded
1451390672299	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1451390672341	DeferredSave.addons.json	DEBUG	Starting write
1451390672372	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'LH', ip: '10.7.14.16', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_66'
Driver info: driver.version: FirefoxDriver

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:135)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.epam.dailybeast.testtask.test.NewsPage.canOpenNewsPage(NewsPage.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
161268431903553903webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1451390671378,"updateDate":1451390671378,"applyBackgroundUpdates":1,"bootstrap":false,"size":3213569,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"45.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1451390671923	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"Zyi2si20fyvo","location":"app-global","version":"43.0.3","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1451359851119,"updateDate":1451359851119,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.3","maxVersion":"43.0.3"}],"targetPlatforms":[]}
1451390671923	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1451390671924	DeferredSave.extensions.json	DEBUG	Save changes
1451390671924	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1451390671924	addons.xpi-utils	DEBUG	Updating add-on states
1451390671925	addons.xpi-utils	DEBUG	Writing add-ons list
1451390671932	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1451390671933	addons.manager	DEBUG	Provider finished startup: XPIProvider
1451390671933	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1451390671933	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1451390671933	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1451390671933	addons.manager	DEBUG	Starting provider: GMPProvider
1451390671937	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1451390671938	addons.manager	DEBUG	Provider finished startup: GMPProvider
1451390671938	addons.manager	DEBUG	Starting provider: PluginProvider
1451390671938	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1451390671938	addons.manager	DEBUG	Provider finished startup: PluginProvider
1451390671938	addons.manager	DEBUG	Completed startup sequence
1451390672106	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1451390672106	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1451390672106	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1451390672154	DeferredSave.extensions.json	DEBUG	Starting write
1451390672287	addons.repository	DEBUG	No addons.json found.
1451390672287	DeferredSave.addons.json	DEBUG	Save changes
1451390672289	DeferredSave.addons.json	DEBUG	Starting timer
1451390672295	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1451390672296	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1451390672296	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1451390672299	DeferredSave.extensions.json	DEBUG	Write succeeded
1451390672299	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1451390672341	DeferredSave.addons.json	DEBUG	Starting write
1451390672372	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:123)
	... 33 more

```

### LINKED ISSUE #14316: [🐛 Bug]: [Grid] Custom node stereotypes are missing in session capabilities
### What happened?
The issue is found after docker-selenium tried to add https://github.com/SeleniumHQ/docker-selenium/pull/2323

Session capabilities running in node Chrome and Edge are missing custom node stereotypes. Meanwhile, node Firefox is fine. See below screenshots

Node stereotypes added `"se:containerName":"my-chrome-name-rr6s5-86shd"`
image

When looking into session capabilities running in this node, could not see `se:containerName`
image

Did the same for node Firefox, we could see `se:containerName` in session capabilities
image

When compare session caps between node Chrome and Firefox, it looks like
image

### How can we reproduce the issue?

```shell
docker-selenium starts Node with

environment:
  - SE_NODE_CONTAINER_NAME: this_specific_node_is_use
```

client binding run tests

ChromeOptions options = new ChromeOptions();
WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), options);
driver.get("https://selenium.dev");
driver.quit();
```
```

### Relevant log output

```shell
[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "126.0", "platformName": "Linux", "goog:chromeOptions": {"binary": "/usr/bin/chromium"}, "se:containerName": "my-chrome-name-b4d69f744-wrg4c"}'
max-sessions = 1
    
Starting Selenium Grid Node...
2024-07-29T02:21:48Asia [Probe.Startup] - Wait for the Node to report its status
2024-07-29T02:21:53Asia [Probe.Startup] - Wait for the Node to report its status
09:21:53.678 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
09:21:53.685 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
09:21:56.377 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub.selenium:4442 and tcp://selenium-hub.selenium:4443
09:21:56.876 INFO [UnboundZmqEventBus.<init>] - Sockets created
09:21:57.878 INFO [UnboundZmqEventBus.<init>] - Event bus ready
2024-07-29T02:21:58Asia [Probe.Startup] - Wait for the Node to report its status
09:21:58.781 INFO [NodeServer.createHandlers] - Reporting self as: http://10.244.147.135:6666
09:21:58.886 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
09:21:59.283 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "126.0","goog:chromeOptions": {"binary": "\u002fusr\u002fbin\u002fchromium"},"platformName": "linux","se:containerName": "my-chrome-name-b4d69f744-wrg4c","se:downloadsEnabled": true,"se:noVncPort": 7900,"se:vncEnabled": true} 1 times
09:21:59.386 INFO [Node.<init>] - Binding additional locator mechanisms: relative
09:22:00.676 INFO [NodeServer$1.start] - Starting registration process for Node http://10.244.147.135:6666
09:22:00.677 INFO [NodeServer.execute] - Started Selenium node 4.23.0 (revision 77010cd): http://10.244.147.135:6666
09:22:00.776 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:22:02.580 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
...

09:27:42.088 INFO [LocalNode.newSession] - Session created by the Node. Id: 56fbb62b30d467cfdedf9d887c28766d, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.182, chrome: {chromedriverVersion: 126.0.6478.182 (5b5d8292ddf..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:42235}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: wss://10.1.0.93/selenium/se..., se:cdpVersion: 126.0.6478.182, se:downloadsEnabled: true, se:name: test_download_file (ChromeT..., se:recordVideo: true, se:screenResolution: 1920x1080, se:vnc: wss://10.1.0.93/selenium/se..., se:vncEnabled: true, se:vncLocalAddress: ws://10.244.147.135:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
```

### Operating System

docker-selenium

### Selenium version

4.23.0

### What are the browser(s) and version(s) where you see this issue?

Chrome, Edge

### What are the browser driver(s) and version(s) where you see this issue?

v127.0

### Are you using Selenium Grid?

4.23.0

### PR DESCRIPTION
**Pull request by pujagani**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Fixes #14316.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Added a new method `readContainerName` in `DriverServiceSessionFactory` to read and set the `se:containerName` capability.
- Integrated the `readContainerName` method into the session creation process to ensure the capability is included in the session response.
- Added a new test `responseCapsShowContainerName` in `LocalNodeTest` to verify that the `se:containerName` capability is correctly included in the session response.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>DriverServiceSessionFactory.java</strong><dd><code>Add method to read and set `se:containerName` capability</code>&nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java

<li>Added method <code>readContainerName</code> to read and set the <code>se:containerName</code> <br>capability.<br> <li> Integrated <code>readContainerName</code> method into the session creation process.<br> <br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14323/files#diff-97ee0dc4a985c8c1aefa101e1a4099ecd7f5d21d4ed1d217b81903abb495e475">+11/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>LocalNodeTest.java</strong><dd><code>Add test for `se:containerName` capability in session response</code></dd></summary>
<hr>

java/test/org/openqa/selenium/grid/node/local/LocalNodeTest.java

<li>Added a new test <code>responseCapsShowContainerName</code> to verify the <br><code>se:containerName</code> capability in session response.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14323/files#diff-84bb17357714d0432cc0193f63d538e258764500a4359a0e07091b83b7d6afa1">+29/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
I thought #14316 was caused by the caps merge in ChromiumOptions, because it works well in Firefox.

**Comment by pujagani** [comment]
So Firefox returns any caps it does not recognize as part of session creation response. But Chromium based browsers filter it out. Hence the difference in behavior. The merge works as expected ( I debugged through it). So this capability needs to be added in the response, similar to what we do for devtools.

**Comment by diemol** [comment]
Understood. Thank you for explaining this.

Should we make this more generic and return all prefixed capabilities?

**Comment by pujagani** [comment]
@VietND96 Also suggested to make it generic. My concern was the "se:" notation is used by cloud providers too. So not sure if adding all such capabilities in the response with that notation is the best approach. What do you think?

**Comment by diemol** [comment]
I know it is used to overwrite the value of `se:cdp`, but I do not know in which other case. I guess my idea is to add the prefixed capabilities from the request if they do not exist already in the response.

**Comment by pujagani** [comment]
I understand. So it is okay to add the options that cloud providers send back in the response? Then we can do this.

**Comment by diemol** [comment]
I would say so. We can always iterate on it.

**Comment by VietND96** [comment]
How the complexity for that generic implementation? Can it be delivered in version 4.24?

**Comment by pujagani** [comment]
I will go add the support to return all prefixed capabilities.

**Review by diemol — APPROVED** [review]
Thank you, @pujagani!

**Comment by VietND96** [comment]
@pujagani , I have checked the Nightly build, but the result didn't meet expectation. Below is response from GraphQL for stereotype and session capabilities. `se:containerName` didn't present in session caps

```json
{
  "data": {
    "session": {
      "id": "fee9aa7d5b9bfed8215dc4c13eb712e8",
      "capabilities": "{\n  \"acceptInsecureCerts\": false,\n  \"browserName\": \"chrome\",\n  \"browserVersion\": \"127.0.6533.119\",\n  \"chrome\": {\n    \"chromedriverVersion\": \"127.0.6533.119 (bdef6783a05f0b3f885591e7d2c7b2aec1a89dea-refs\\u002fbranch-heads\\u002f6533@{#1999})\",\n    \"userDataDir\": \"\\u002ftmp\\u002f.org.chromium.Chromium.ayWmnw\"\n  },\n  \"fedcm:accounts\": true,\n  \"goog:chromeOptions\": {\n    \"debuggerAddress\": \"localhost:46525\"\n  },\n  \"networkConnectionEnabled\": false,\n  \"pageLoadStrategy\": \"normal\",\n  \"platformName\": \"linux\",\n  \"proxy\": {\n  },\n  \"se:bidiEnabled\": false,\n  \"se:cdp\": \"wss:\\u002f\\u002f10.1.0.245\\u002fselenium\\u002fsession\\u002ffee9aa7d5b9bfed8215dc4c13eb712e8\\u002fse\\u002fcdp\",\n  \"se:cdpVersion\": \"127.0.6533.119\",\n  \"se:downloadsEnabled\": true,\n  \"se:name\": \"test_play_video (ChromeTests)\",\n  \"se:recordVideo\": true,\n  \"se:screenResolution\": \"1920x1080\",\n  \"se:vnc\": \"wss:\\u002f\\u002f10.1.0.245\\u002fselenium\\u002fsession\\u002ffee9aa7d5b9bfed8215dc4c13eb712e8\\u002fse\\u002fvnc\",\n  \"se:vncEnabled\": true,\n  \"se:vncLocalAddress\": \"ws:\\u002f\\u002f10.244.251.137:7900\",\n  \"setWindowRect\": true,\n  \"strictFileInteractability\": false,\n  \"timeouts\": {\n    \"implicit\": 0,\n    \"pageLoad\": 300000,\n    \"script\": 30000\n  },\n  \"unhandledPromptBehavior\": \"dismiss and notify\",\n  \"webauthn:extension:credBlob\": true,\n  \"webauthn:extension:largeBlob\": true,\n  \"webauthn:extension:minPinLength\": true,\n  \"webauthn:extension:prf\": true,\n  \"webauthn:virtualAuthenticators\": true\n}",
      "startTime": "21/08/2024 01:45:57",
      "uri": "http://10.244.251.137:6666",
      "nodeId": "b1f84412-a065-472d-8a83-c0eba6de300b",
      "nodeUri": "http://10.244.251.137:6666",
      "sessionDurationMillis": "1016",
      "slot": {
        "id": "62afd8fb-a123-4497-b475-8c0c383ff6c5",
        "stereotype": "{\n  \"browserName\": \"chrome\",\n  \"browserVersion\": \"127.0\",\n  \"goog:chromeOptions\": {\n    \"binary\": \"\\u002fusr\\u002fbin\\u002fchromium\"\n  },\n  \"platformName\": \"linux\",\n  \"se:containerName\": \"my-chrome-name-85c6f9fb-tmcqf\",\n  \"se:downloadsEnabled\": true,\n  \"se:noVncPort\": 7900,\n  \"se:vncEnabled\": true\n}",
        "lastStarted": "21/08/2024 01:45:57"
      }
    }
  }
}
```

**Comment by pujagani** [comment]
Which graphQL endpoint are you calling?

**Comment by VietND96** [comment]
@pujagani, the endpoint is selenium-hub:4444/graphql with query as below
> '{"query":"{ session (id: \"'${SESSION_ID}'\") { id, capabilities, startTime, uri, nodeId, nodeUri, sessionDurationMillis, slot { id, stereotype, lastStarted } } } "}'

**Comment by VietND96** [comment]
In Hub logs, it printed caps as below, `se:containerName` also not included
> 21:26:15.825 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: a4b0bdac43d694550b2fa54eff99519e 
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.84, chrome: {chromedriverVersion: 128.0.6613.84 (606aa55c7d68..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:33739}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:bidiEnabled: false, se:cdp: wss://10.1.0.47:31444/selen..., se:cdpVersion: 128.0.6613.84, se:downloadsEnabled: true, se:name: test_download_file (ChromeT..., se:recordVideo: true, se:screenResolution: 1920x1080, se:vnc: wss://10.1.0.47:31444/selen..., se:vncEnabled: true, se:vncLocalAddress: ws://10.244.103.12:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}

**Comment by pujagani** [comment]
Thank you for checking. Let me triage this further.

File: java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java [hunk 1]
```diff
@@ -300,6 +301,23 @@ private Capabilities readVncEndpoint(Capabilities requestedCaps, Capabilities re
...
+
+    PersistentCapabilities returnPrefixedCaps = new PersistentCapabilities(returnedCaps);
+
+    Map<String, Object> requestedCapsMap = requestedCaps.asMap();
+    Map<String, Object> returnedCapsMap = returnedCaps.asMap();
+
+    requestedCapsMap.forEach(
+        (k, v) -> {
+          if (k.startsWith("se:") && !returnedCapsMap.containsKey(k)) {
+            returnPrefixedCaps.setCapability(k, v);
```
Comment (diemol) [inline java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java:314]: Maybe the issue is that `setCapability` returns a new `PersistentCapabilities` object and does not modify the current one.

Comment (pujagani) [reply java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java:314]: Yes, exactly. I fixed it via https://github.com/SeleniumHQ/selenium/commit/ef1b4221b299dfce1215411f69b99fb76bb1807c.

**Comment by pujagani** [comment]
It was a quick fix, but how to add a test for it is tricky. We don't have an end-to-end test for DriverServiceSessionFactory. 
However, locally, I am now seeing the expected result.

```
{
    "data": {
        "session": {
            "id": "d83a88c7cd21da860faab12db2ce159c",
            "capabilities": "{\n  \"acceptInsecureCerts\": false,\n  \"browserName\": \"chrome\",\n  \"browserVersion\": \"127.0.6533.120\",\n  \"chrome\": {\n    \"chromedriverVersion\": \"127.0.6533.119 (bdef6783a05f0b3f885591e7d2c7b2aec1a89dea-refs\/branch-heads\/6533@{#1999})\",\n    \"userDataDir\": \"\/var\/folders\/r2\/3dlyvgq1275gthvnwn_c5qy40000gq\/T\/.org.chromium.Chromium.F0Seh7\"\n  },\n  \"fedcm:accounts\": true,\n  \"goog:chromeOptions\": {\n    \"debuggerAddress\": \"localhost:56775\"\n  },\n  \"networkConnectionEnabled\": false,\n  \"pageLoadStrategy\": \"normal\",\n  \"platformName\": \"mac\",\n  \"proxy\": {\n  },\n  \"se:bidiEnabled\": false,\n  \"se:cdp\": \"ws:\/\/192.168.31.67:4444\/session\/d83a88c7cd21da860faab12db2ce159c\/se\/cdp\",\n  \"se:cdpVersion\": \"127.0.6533.120\",\n  \"se:containerName\": \"my-chrome-node\",\n  \"setWindowRect\": true,\n  \"strictFileInteractability\": false,\n  \"timeouts\": {\n    \"implicit\": 0,\n    \"pageLoad\": 300000,\n    \"script\": 30000\n  },\n  \"unhandledPromptBehavior\": \"dismiss and notify\",\n  \"webauthn:extension:credBlob\": true,\n  \"webauthn:extension:largeBlob\": true,\n  \"webauthn:extension:minPinLength\": true,\n  \"webauthn:extension:prf\": true,\n  \"webauthn:virtualAuthenticators\": true\n}",
            "startTime": "23/08/2024 18:45:44",
            "uri": "http://192.168.31.67:4444",
            "nodeId": "1532f5f6-db5a-4851-9466-e37c7d294607",
            "nodeUri": "http://192.168.31.67:4444",
            "sessionDurationMillis": "30347",
            "slot": {
                "id": "a18a014a-fbcc-4d5d-9cb2-67225378d7c9",
                "stereotype": "{\n  \"browserName\": \"chrome\",\n  \"platformName\": \"mac\",\n  \"se:containerName\": \"my-chrome-node\"\n}",
                "lastStarted": "23/08/2024 18:45:44"
            }
        }
    }
}
```
