### PR TITLE
[js] [atoms] Fixed text transformation issue with text-transform: capitalize

### LINKED ISSUE #14271: [🐛 Bug]: Text transformation issue with `text-transform: capitalize;` using Selenium WebDriver with Firefox 127.0.2
### What happened?

**Description:**
There is an issue with the `text-transform: capitalize;` CSS property when using Selenium WebDriver with Firefox 127.0.2. The text transformation does not handle accented characters correctly, resulting in incorrect capitalization.

**Steps to Reproduce:**
1. Install Node.js.
2. Create a new project and install Selenium WebDriver.
   ```bash
   npm init -y
   npm install selenium-webdriver // last version
   ```
3. Download `geckodriver 0.34` and place it in a specific directory.
4. Create the following JavaScript script (`selenium_example.js`):

```javascript
const { Builder, By, until } = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');
const path = require('path');

const geckodriverPath = path.join(process.env.HOME, 'gecko/geckodriver');  // Adjust this path

(async function example() {
    let options = new firefox.Options();
    options.setBinary(geckodriverPath);

    let driver = new Builder()
        .forBrowser('firefox')
        .setFirefoxOptions(options)
        .build();

    try {
        const url = 'file:///home/user/test/bug/index.html';

        await driver.get(url);

        await driver.wait(until.elementLocated(By.tagName('h1')), 10000);

        let element = await driver.findElement(By.tagName('h1'));

        let text = await element.getText();

        console.log(`response: ${text}`);
    } finally {
        await driver.quit();
    }
})();
```

5. Create the following HTML file (`index.html`):

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bug Test</title>
    <style>
        h1 {
            text-transform: capitalize;
        }
    </style>
</head>
<body>
    <h1>Fecha de expiración</h1>
</body>
</html>
```

6. Run the script:
   ```bash
   node selenium_example.js
   ```

**Expected Behavior:**
The output should be:
```
response: Fecha De Expiración
```

**Actual Behavior:**
The output is:
```
response: Fecha De ExpiraciÓN
```

**Additional Information:**
- **Operating System:** Fedora 40
- **Node.js:** v20.12.2
- **Selenium WebDriver:** 4.22.0
- **geckodriver:** 0.34.0 (c44f0d09630a 2024-01-02 15:36 +0000)
- **Firefox:** 127.0.2

This issue started occurring after updating to Firefox 127.0.2. It appears that the `text-transform: capitalize;` CSS property does not handle accented characters correctly.

**Console Output:**
No errors in the console.

---

### How can we reproduce the issue?

```shell
already described
```

### Relevant log output

```shell
already described
```

### Operating System

Fedora 40

### Selenium version

4.22.0

### What are the browser(s) and version(s) where you see this issue?

Firefox: 127.0.2

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver: 0.34.0 (c44f0d09630a 2024-01-02 15:36 +0000)

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by vicky-iv**
### 🔗 Related Issues
Fixes #14271

### 💥 What does this PR do?
Fixes incorrect capitalization behavior for text-transform: capitalize, addressing:
 - Accented Latin letters (e.g., “expiración” → “Expiración”, not “ExpiraciÓN”).
 - Enye (mañana -> Mañana)

### 🔧 Implementation Notes
Replaced the previous boundary regex:

 - First step uses a negated “separator” class that treats ASCII letters, extended Latin letters (\u00C0–\u02AF, \u1E00–\u1EFF) and combining marks (\u0300–\u036F, \u1AB0–\u1AFF, \u1DC0–\u1DFF) as in-word characters, and excludes _ and apostrophes from being boundaries (so we don’t split snake_case or contractions).

 - Second step: a small second regex capitalizes the first letter after an opening _ or * only when those symbols act as wrappers (preceded by start or a non-word), avoiding interference with snake_case.

All tests from the text_test.html are passed locally:
 - Firefox:
image

 - Chrome:
image

 - Safari:
image

### 💡 Additional Considerations
Scope limited to Latin scripts + circled letters; other scripts (Greek/Cyrillic/etc.) can be added by extending ranges if needed.

### 🔄 Types of changes
- Bug fix (backwards compatible)

___

### **PR Type**
Bug fix

___

### **Description**
- Fixed text-transform: capitalize for accented Latin letters

- Added support for enye and extended Unicode ranges

- Improved boundary detection to preserve snake_case

- Added test cases for Spanish accented characters

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["Old regex boundary detection"] --> B["Enhanced Unicode-aware regex"]
  B --> C["Preserve snake_case"]
  B --> D["Support accented letters"]
  E["Add test cases"] --> F["Spanish characters validation"]
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>dom.js</strong><dd><code>Enhanced text capitalization with Unicode support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

javascript/atoms/dom.js

<ul><li>Replaced simple boundary regex with Unicode-aware pattern<br> <li> Added support for extended Latin and combining marks ranges<br> <li> Implemented two-step capitalization to handle edge cases<br> <li> Preserved snake_case and contractions from incorrect splitting</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16275/files#diff-53bbf9a76b3e18a714284bd37ffdbcb670cbf537319cdaee94aacca31bcc497d">+9/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>text_test.html</strong><dd><code>Added Unicode capitalization test cases</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

javascript/atoms/test/text_test.html

<ul><li>Added test cases for Spanish accented characters<br> <li> Fixed whitespace expectations in preformatted text tests<br> <li> Added validation for "expiración" and "mañana" capitalization</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16275/files#diff-dbdaac7fc50c04f122f9c085cbf1d23abb99cc920169db9a110249d8abbfa12a">+12/-2</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: javascript/atoms/dom.js [hunk 1]
```diff
@@ -1173,11 +1173,18 @@ bot.dom.appendVisibleTextLinesFromTextNode_ = function (textNode, lines,
...
+    var re = /(^|[^'_0-9A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9\u0300-\u036F\u1AB0-\u1AFF\u1DC0-\u1DFF])([A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9])/g;
     text = text.replace(re, function () {
       return arguments[1] + arguments[2].toUpperCase();
     });
+
+    // 2) capitalize after opening "_" or "*"
+    // Preceded by start or a non-word (so it won't fire for snake_case)
+    re = /(^|[^'_0-9A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9])([_*])([A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24D0-\u24E9])/g;
+    text = text.replace(re, function () {
+      return arguments[1] + arguments[2] + arguments[3].toUpperCase();
```
Comment (Usielrivas) [inline javascript/atoms/dom.js:1186]: Here you can remove the magic numbers and leave something more descriptive like:

```
    text = text.replace(re, function (_match, prefix, divider, char) {
      return prefix + divider + char.toUpperCase();
    });

```

Comment (vicky-iv) [reply javascript/atoms/dom.js:1186]: Sure, I just followed the existing implementation and coding style

Comment (Usielrivas) [reply javascript/atoms/dom.js:1186]: No worries, it's just a coding tip.

**Review by diemol — APPROVED** [review]
Thank you, @vicky-iv!
