### PR TITLE
A Hub API that can query all running sessions.

### LINKED ISSUE #6070: Exception when retrieving a list of sessions from a hub
## Meta -
OS:  Linux
Selenium Version:  Selenium Grid Hub v.3.12.0

## Expected Behavior -
When I make a GET /wd/hub/sessions request on a node I get the following response:
```json
{"status":0,"value":[]}
```
If i would make this request to a hub I would expect a similar response.

## Actual Behavior -
When I make that same request to a hub I get the following error:
```json
{
    "sessionId": null,
    "status": 13,
    "value": {
        "class": "org.openqa.grid.common.exception.GridException",
        "error": "unknown error",
        "message": "Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[]",
        "stackTrace": [
            {
                "className": "org.openqa.grid.internal.ActiveTestSessions",
                "fileName": "ActiveTestSessions.java",
                "lineNumber": 120,
                "methodName": "getExistingSession"
            },
            {
                "className": "org.openqa.grid.internal.DefaultGridRegistry",
                "fileName": "DefaultGridRegistry.java",
                "lineNumber": 380,
                "methodName": "getExistingSession"
            },
            {
                "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
                "fileName": "RequestHandler.java",
                "lineNumber": 241,
                "methodName": "getSession"
            },
            {
                "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
                "fileName": "RequestHandler.java",
                "lineNumber": 123,
                "methodName": "process"
            },
            {
                "className": "org.openqa.grid.web.servlet.DriverServlet",
                "fileName": "DriverServlet.java",
                "lineNumber": 86,
                "methodName": "process"
            },
            {
                "className": "org.openqa.grid.web.servlet.DriverServlet",
                "fileName": "DriverServlet.java",
                "lineNumber": 64,
                "methodName": "doGet"
            },
            {
                "className": "javax.servlet.http.HttpServlet",
                "fileName": "HttpServlet.java",
                "lineNumber": 687,
                "methodName": "service"
            },
            {
                "className": "javax.servlet.http.HttpServlet",
                "fileName": "HttpServlet.java",
                "lineNumber": 790,
                "methodName": "service"
            },
            {
                "className": "org.seleniumhq.jetty9.servlet.ServletHolder",
                "fileName": "ServletHolder.java",
                "lineNumber": 860,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
                "fileName": "ServletHandler.java",
                "lineNumber": 535,
                "methodName": "doHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 143,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.security.SecurityHandler",
                "fileName": "SecurityHandler.java",
                "lineNumber": 548,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
                "fileName": "HandlerWrapper.java",
                "lineNumber": 132,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 190,
                "methodName": "nextHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
                "fileName": "SessionHandler.java",
                "lineNumber": 1595,
                "methodName": "doHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 188,
                "methodName": "nextHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
                "fileName": "ContextHandler.java",
                "lineNumber": 1253,
                "methodName": "doHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 168,
                "methodName": "nextScope"
            },
            {
                "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
                "fileName": "ServletHandler.java",
                "lineNumber": 473,
                "methodName": "doScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
                "fileName": "SessionHandler.java",
                "lineNumber": 1564,
                "methodName": "doScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 166,
                "methodName": "nextScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
                "fileName": "ContextHandler.java",
                "lineNumber": 1155,
                "methodName": "doScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 141,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
                "fileName": "HandlerWrapper.java",
                "lineNumber": 132,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.Server",
                "fileName": "Server.java",
                "lineNumber": 530,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.HttpChannel",
                "fileName": "HttpChannel.java",
                "lineNumber": 347,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.HttpConnection",
                "fileName": "HttpConnection.java",
                "lineNumber": 256,
                "methodName": "onFillable"
            },
            {
                "className": "org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback",
                "fileName": "AbstractConnection.java",
                "lineNumber": 279,
                "methodName": "succeeded"
            },
            {
                "className": "org.seleniumhq.jetty9.io.FillInterest",
                "fileName": "FillInterest.java",
                "lineNumber": 102,
                "methodName": "fillable"
            },
            {
                "className": "org.seleniumhq.jetty9.io.ChannelEndPoint$2",
                "fileName": "ChannelEndPoint.java",
                "lineNumber": 124,
                "methodName": "run"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
                "fileName": "EatWhatYouKill.java",
                "lineNumber": 247,
                "methodName": "doProduce"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
                "fileName": "EatWhatYouKill.java",
                "lineNumber": 140,
                "methodName": "produce"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
                "fileName": "EatWhatYouKill.java",
                "lineNumber": 131,
                "methodName": "run"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread",
                "fileName": "ReservedThreadExecutor.java",
                "lineNumber": 382,
                "methodName": "run"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool",
                "fileName": "QueuedThreadPool.java",
                "lineNumber": 708,
                "methodName": "runJob"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2",
                "fileName": "QueuedThreadPool.java",
                "lineNumber": 626,
                "methodName": "run"
            },
            {
                "className": "java.lang.Thread",
                "fileName": "Thread.java",
                "lineNumber": 748,
                "methodName": "run"
            }
        ],
        "stacktrace": "org.openqa.grid.common.exception.GridException: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[]\n\tat org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:120)\n\tat org.openqa.grid.internal.DefaultGridRegistry.getExistingSession(DefaultGridRegistry.java:380)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:241)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:123)\n\tat org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)\n\tat org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:64)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.Server.handle(Server.java:530)\n\tat org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)\n\tat org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)\n\tat org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)\n\tat org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)\n\tat org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)\n\tat org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)\n\tat java.lang.Thread.run(Thread.java:748)\n"
    }
}
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #6070

The API can be accessed via 
http://<IP:Port>/grid/api/sessions.

Both GET and POST are supported and result in the
same behavior.

A typical response can look like below (intentionally
trimmed the capabilities to reduce verbosity)

```json
{
  "proxies": [
    {
      "proxyId": "http://192.168.1.6:5555",
      "proxyRemoteHost": "http://192.168.1.6:5555",
      "sessions": {
        "status": 0,
        "value": [
          {
            "id": "df8aa16d-1d52-2e43-b584-2f9df586b0f3",
            "capabilities": {}
          },
          {
            "id": "f85f5641-e6de-3642-913a-a45aafdb85ad",
            "capabilities": {}
          }
        ]
      }
    },
    {
      "proxyId": "http://192.168.1.6:5556",
      "proxyRemoteHost": "http://192.168.1.6:5556",
      "sessions": {
        "status": 0,
        "value": [
          {
            "id": "f4df4fbd-96ee-e042-ab43-40a33698d1e9",
            "capabilities": {}
          }
        ]
      }
    }
  ],
  "success": true
}
```

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @shs96c @barancev - Can one of you please help take a look at this ?

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+  private List<Map<String, Object>> extractSessionsFromAllProxies() {
+    List<Map<String, Object>> results = new LinkedList<>();
+    List<RemoteProxy> proxies = getRegistry().getAllProxies().getBusyProxies();
+    for (RemoteProxy proxy : proxies) {
+      Map<String, Object> sessionsInProxy = new TreeMap<>(extractSessionInfo(proxy));
+      if (sessionsInProxy.isEmpty()) {
+        continue;
+      }
+      Map<String, Object> res = new TreeMap<>();
+      res.put("proxyId", proxy.getId());
```
Comment (shs96c) [inline java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: This is already going to be returned as a list of proxies. Having the word "`proxy`" seems redundant.

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+
+  private static Map<String, Object> extractSessionInfo(RemoteProxy proxy) {
+    try {
+      URL url = proxy.getRemoteHost();
+      HttpRequest req = new HttpRequest(HttpMethod.GET, "/wd/hub/sessions");
+      HttpResponse rsp = proxy.getHttpClient(url).execute(req);
+      try (InputStream in = new ByteArrayInputStream(asBytes(rsp));
+           Reader reader = new InputStreamReader(in, getContentEncoding(rsp))) {
+        Object body = new Json().newInput(reader).read(Object.class);
+        if (body instanceof Map) {
```
Comment (shs96c) [inline java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: Instead of doing this, you can get the json coercer to do all the hard work:

```
Map<String, Object> body = json.newInput(reader).read(Json.MAP_TYPE);
```

Also, you're going to leak the `JsonInput`: best open that in the try statement above.

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+          return (Map<String, Object>) body;
+        }
+      } catch (JsonException e) {
+        // Nothing to do --- poorly formed payload.
+      }
+    } catch (IOException e) {
+      throw new GridException(e.getMessage());
+    }
+    return new TreeMap<>();
```
Comment (shs96c) [inline java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: We don't want to indicate some form of error has occurred?

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+  }
+
+  private static byte[] asBytes(HttpResponse rsp) {
+    InputStream stream = rsp.consumeContentStream();
```
Comment (shs96c) [inline java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: Heavens. Just call `rsp.getContent()`. You're not saving any memory doing this.

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 5]
```diff
@@ -0,0 +1,154 @@
...
+    try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
+      ByteStreams.copy(stream, bos);
+      return bos.toByteArray();
+    } catch (IOException e) {
+      throw new GridException(e.getMessage());
+    }
+  }
+
+  private static Charset getContentEncoding(HttpResponse rsp) {
```
Comment (shs96c) [inline java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: And this is `rsp.getContentEncoding()`

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+  protected void doGet(HttpServletRequest req, HttpServletResponse rsp) throws IOException {
+    process(rsp);
+  }
+
+  @Override
+  protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
+    if (req.getInputStream() != null) {
+      process(resp);
+    } else {
+      process(resp);
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: Fixed it. Initially I was thinking of supporting something like giving the ability to query sessions given a node. Forgot to remove the branching, when I didn't go forward with the implementation.

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 7]
```diff
@@ -0,0 +1,154 @@
...
+    }
+  }
+
+  protected void process(HttpServletResponse response) throws IOException {
+    response.setContentType("application/json");
+    response.setCharacterEncoding("UTF-8");
+    response.setStatus(200);
+    Map<String, Object> proxies = new TreeMap<>();
+    try (Writer writer = response.getWriter(); JsonOutput out = json.newOutput(writer)) {
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: Fixed.

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+  }
+
+  private static Map<String, Object> extractSessionInfo(RemoteProxy proxy) {
+    try {
+      URL url = proxy.getRemoteHost();
+      HttpRequest req = new HttpRequest(HttpMethod.GET, "/wd/hub/sessions");
+      HttpResponse rsp = proxy.getHttpClient(url).execute(req);
+      try (InputStream in = new ByteArrayInputStream(asBytes(rsp));
+           Reader reader = new InputStreamReader(in, getContentEncoding(rsp))) {
+        Object body = new Json().newInput(reader).read(Object.class);
```
[the remark this answers is not in the document]
Comment (krmahadevan) [reply java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: Fixed.

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java (hunk 1 above)
Comment (krmahadevan) [reply java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: The current sessions payload, has no information about the proxy. That is why added both the proxyId and proxyRemoteHost so that the user gets to know as to for which proxy does the sessions info belong to.

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java (hunk 3 above)
Comment (krmahadevan) [reply java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: Fixed it. The status gets flipped to `false` if there was any difficulty in extracting sessions info

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java (hunk 4 above)
Comment (krmahadevan) [reply java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: Fixed. I think I borrowed that code from somewhere :)

File: java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java (hunk 5 above)
Comment (krmahadevan) [reply java/server/src/org/openqa/grid/web/servlet/NodeSessionsServlet.java]: fixed.

**Comment by krmahadevan** [comment]
@shs96c 

> This is missing tests, so it'll be easy to introduce accidental regressions.

I was initially confused as to what sort of tests I add because this new servlet internally makes a call to `WebDriverServlet` running in the node. So didn't know how to fake that out. Ended up writing a E2E test which tests the functionality by spinning a grid hub and node.

> The approach taken here is very "bare metal": we're basically exposing the internals of the current grid to the world. Is this the approach we want to take, or would we prefer something that explains the domain better? I'm perfectly happy if the answer is "bare metal to get us off the ground", as I think we're allowed to iterate on Grid functionality with greater freedom than anything on the client side.

The ask in #6070  was explicitly to have the capability of listing out all the sessions running in the Hub via an API. Please let me know if there's any other way of giving this capability. I will alter my PR accordingly.

I have addressed the review comments. Please help take a look.

**Comment by krmahadevan** [comment]
@shs96c - thank you so much for merging the other two PRs. Can you please check if this one needs any additional work or if it can be merged as well ?

**Comment by krmahadevan** [comment]
Rebased off of `master` and pushed in the updated branch.
