### PR TITLE
[dotnet] [bidi] Do not throw when CallFunction or Evaluate return exceptional result (breaking change)

### LINKED ISSUE #15414: [🚀 Feature]: [dotnet] [bidi] Don't throw exception when CallFunction/Evaluate in Script module
### Feature and motivation

```csharp
await context.Script.CallFunctionAsync("() => { return ['hi']; }", false);
```

It throws an .Net exception rather than returning `EvaluateResult` BiDi object.

```
script.EvaluateResult = (
  script.EvaluateResultSuccess /
  script.EvaluateResultException
)
```

Now, .Net methods throw if the result is `EvaluateResultException`. It is not ideal, low-level binding should not introduce additional logic on top of specification.

Why:
- We are hiding all data included into `EvaluateResultException`, trying to include it in .Net Exception type.
- If in future new derived type will be introduced in the spec (like "PartiallySuccess"), then we will be in **s (problematic situation)

### Usage example

Before:

```csharp
public Task<EvaluateResult.Success> CallFunctionAsync(...)
```

After:
```csharp
public Task<EvaluateResult> CallFunctionAsync(...)
```

**NOTE**: Keeping in mind implicit/explicit type conversions in .NET.

### PR DESCRIPTION
**Pull request by RenderMichael**
### Description
In an effort for Selenium's raw BiDi to return the exact response from the endpoint, we should not throw exceptions unless the opt-in `ThrowOnError()` method is called.

### Motivation and Context

Fixes https://github.com/SeleniumHQ/selenium/issues/15414

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Updated `EvaluateAsync` and `CallFunctionAsync` methods to handle exceptional results without throwing exceptions directly.
  - Introduced `ThrowOnError` method in `EvaluateResult` to centralize error handling.
  - Modified return types of `EvaluateAsync` and `CallFunctionAsync` to `EvaluateResult` for consistency.

- Enhanced error handling by refining `ScriptEvaluateException` to include detailed stack trace information.

- Adjusted test cases to validate the new `ThrowOnError` behavior and ensure proper handling of exceptional results.
  - Updated assertions in test cases to check for `EvaluateResultSuccess` and use `ThrowOnError` for result validation.

- Improved serialization logic in `ChannelLocalValue` to ensure proper JSON property naming.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td><strong>BrowsingContextScriptModule.cs</strong><dd><code>Refactored <code>EvaluateAsync</code> and <code>CallFunctionAsync</code> methods for error <br>handling</code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-22b8fd1cae01d6e99f522989e76b88a7171b7549a995b53b1a57839d804409f7">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>EvaluateCommand.cs</strong><dd><code>Added <code>ThrowOnError</code> method to <code>EvaluateResult</code> for centralized error <br>handling</code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-2c814f092ccb5092dff7d4668b006c35c6353d2b400075225c699e446afd285d">+12/-1</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>LocalValue.cs</strong><dd><code>Improved JSON serialization for `ChannelLocalValue`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-b2d3bd83230255db2e435ac34700a0af0595469211636058e6eb477107171b22">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>ScriptEvaluateException.cs</strong><dd><code>Enhanced exception message with detailed stack trace</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-5872f5333a5a564b72e342a8a776d2f7d4959f54eb2c8f959718d05ca1e43106">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>ScriptModule.cs</strong><dd><code>Removed direct exception throwing in <code>EvaluateAsync</code> and <br><code>CallFunctionAsync</code></code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-9f5eefb2855c2156fe6f920c1444f437415e90fe97801f55062160b6ebd1c4d9">+7/-16</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td><strong>CallFunctionLocalValueTest.cs</strong><dd><code>Updated tests to validate <code>ThrowOnError</code> behavior for <code>CallFunctionAsync</code></code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-30e71e855b2436173edf5ce35368b843613bc33c9601155c03f0a249d79ea27d">+88/-100</a></td>

</tr>

<tr>
  <td><strong>CallFunctionParameterTest.cs</strong><dd><code>Adjusted parameter tests to handle <code>ThrowOnError</code> in <code>CallFunctionAsync</code></code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-2211a55aa8f7fbbe821213f4f0a771f85a33b7b639fc7bbe2e4bd38a48c85608">+23/-22</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>CallFunctionRemoteValueTest.cs</strong><dd><code>Refined remote value tests to use <code>ThrowOnError</code> for result validation</code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-5e1e64c5c3e62080b8af5a569d0a2dd326417dbeebb33d00a714d7324953f4da">+38/-38</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>EvaluateParametersTest.cs</strong><dd><code>Enhanced evaluation parameter tests with `ThrowOnError` validation</code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-8be27a9d0c3975df6c9e97783134da9a302a70cbe6cf351afa7f3a6605823862">+12/-11</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>ScriptCommandsTest.cs</strong><dd><code>Updated script command tests to validate `ThrowOnError` behavior</code></dd></td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15521/files#diff-f556a10a263ca5a37c0ac56fc1c010d1defc3b1dc2d99ec62af45d8b31ae81a3">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

File: dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs [hunk 1]
```diff
@@ -29,5 +29,5 @@ public class ScriptEvaluateException(EvaluateResultException evaluateResultExcep
 
     public long ColumNumber => _evaluateResultException.ExceptionDetails.ColumnNumber;
 
-    public override string Message => $"{Text}{Environment.NewLine}{_evaluateResultException.ExceptionDetails.StackTrace}";
+    public override string Message => $"{Text}{Environment.NewLine}{string.Join(Environment.NewLine, _evaluateResultException.ExceptionDetails.StackTrace.CallFrames)}";
```
Comment (RenderMichael) [inline dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs]: For error like this:
image

Before:
image

After:
image

File: dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs [hunk 2]
```diff
@@ -39,7 +39,18 @@ public record EvaluateOptions : CommandOptions
 //[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
 //[JsonDerivedType(typeof(EvaluateResultSuccess), "success")]
 //[JsonDerivedType(typeof(EvaluateResultException), "exception")]
-public abstract record EvaluateResult;
+public abstract record EvaluateResult
+{
+    public EvaluateResultSuccess ThrowOnError()
```
Comment (RenderMichael) [inline dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: Good name?

File: dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs (hunk 1 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs]: We can even remove `ScriptEvaluateException` type. And throw general `BiDiException` which takes already formatted string from `EvaluateResultError` record type. Then what we need, just improve formatting of `EvaluateResultError` to string (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#built-in-formatting-for-display).

File: dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs (hunk 2 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: `EnsureSuccess()` or `ToSuccess()` or `AsSuccess()` is better IMHO. As I know `EnsureSuccess()` should not convert, I have no strong opinion.

Comment (nvborisenko) [inline dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: What if just return `RemoteValue` at once?

Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: If we consider https://github.com/SeleniumHQ/selenium/pull/15521#discussion_r2024801785, then I propose `RemoteValue AsSuccessResult()`.

**Comment by nvborisenko** [comment]
Not related to this PR, I added a prefix `(breaking change)` to reflect this in CHANGELOG. Thus users will be notified about potential breaking changes.

File: dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs (hunk 2 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: How I feel it: `.To*()` should allocate new object, `As*()` should return a reference.

Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: That is too much magic in my opinion. the two methods which have JS evaluation, `EvaluateAsync` and `CallFunctionAsync`, both have generic overloads which will de-serialize to the correct type. Otherwise, users have access to the Success type directly. It is trivial to do `.Result` if they need the `RemoteValue`.

Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: I agree with the `As*()` naming style. Going with `AsSuccessResult()`.

I mentioned in the other comment why I think this should still return an `EvaluateResultSuccess`.

However, I do not feel strongly about it, since this is just a helper method anyway (should this be an extension?). In our code, we call `EvaluateResultSuccess.Realm` two times, and the remaining 68 times we access `.Result` immediately.

While typing this message, I have been convinced. Changing the return to `RemoteValue`.

Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: Done.

File: dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs (hunk 1 above)
Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs]: I think a special exception type is necessary, because we can expose the `ExceptionDetails` directly. User code can be like:

```C#
try
{
    var res = await context.Script.EvaluateAsync("maybe throws", false);
}
catch (ScriptEvaluateException ex)
{
    Console.WriteLine(ex.EvaluateResultException);
}
```

I changed the `ScriptEvaluateException` to reflect this, let me know what you think.

File: dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs [hunk 3]
```diff
@@ -39,7 +39,20 @@ public record EvaluateOptions : CommandOptions
...
+    public RemoteValue AsSuccessResult()
+    {
+        if (this is EvaluateResultSuccess success)
+        {
+            return success.Result;
+        }
+
+        var exceptionResult = (EvaluateResultException)this;
+
+        throw new ScriptEvaluateException(exceptionResult.ExceptionDetails);
```
Comment (nvborisenko) [inline dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: I really propose to remove this exception type.

- If spec introduces new `PartiallyException` type, we again will be in problematic situation.

How to negotiate: just throw `BiDiException` with info about something like "expected success but got 'blah blah'".

File: dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs [hunk 4]
```diff
@@ -160,9 +160,10 @@ public record BigIntLocalValue(string Value) : PrimitiveProtocolLocalValue;
 
 public record ChannelLocalValue(ChannelProperties Value) : LocalValue
 {
-    // TODO: Revise why we need it
+    // AddPreloadScript takes arguments typed as ChannelLocalValue but still requires "type":"channel"
     [JsonInclude]
-    internal string type = "channel";
+    [JsonPropertyName("type")]
```
Comment (nvborisenko) [inline dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs]: Unnecessary attribute, in my head we will just rename property rather than support backward compatibility. Because if we will not rename properties according spec (even if it is breaking change), we will become to a chaos where the .NET types mess weakly correlated to spec.

File: dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs (hunk 3 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: All right, and this "blah blah" can be just `commandResult.ToString()` (and here the magic of formatting of `record` to string helps).

File: dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs [hunk 5]
```diff
@@ -160,9 +160,10 @@ public record BigIntLocalValue(string Value) : PrimitiveProtocolLocalValue;
...
+    internal string Type => "channel";
```
Comment (nvborisenko) [inline dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs:304]: Do you know any difference:
```csharp
internal string Type { get: } = "channel";
```

Any performance impact?

(minor question, resolve it without answers)

Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs:304]: https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboLIE8AquADgKboDey61mGUcADOgILoC8AfOgEQCGARgGNuAbio1x1NJkboAQhXQBzEgBcR6AL7seA4WKQ10k2jIBsMpgGF2XPkNEmT0+hfpMAIopXqt1NroOBppAA===

Static is better? If it is true... and it is friendly with json serialization, I propose to introduce this rule.

File: dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs (hunk 1 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/ScriptEvaluateException.cs]: Ah stop, this PR is about `Do not throw when CallFunction or Evaluate return exceptional result` :D So definitely remove this special exception.

Moreover we will support limited exceptions defined by spec: https://w3c.github.io/webdriver-bidi/#errors, so just prefer something in BCL.

File: dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs (hunk 5 above)
Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/Modules/Script/LocalValue.cs:304]: I think a property that results a `const` has better performance, but I chose it for style. I have no problem with an auto property. I think it definitely should not be a field, though.

File: dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs (hunk 3 above)
Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: Changed to use `BiDiException` + exception formatting. Example:

image

Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: Letting you know in advance that even `BiDiException` is unnecessary. We will support only spec defined errors: https://w3c.github.io/webdriver-bidi/#errors. I introduced `BiDiException` a long time ago just to not think about what exception to throw. Time to revisit, definitely not in this PR.

Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: I simplified it:

```csharp
await context.Script.EvaluateAsync<int>("boom", true);
```

```
System.InvalidCastException : Expected the result to be EvaluateResultSuccess, but received EvaluateResultException { ExceptionDetails = ExceptionDetails { ColumnNumber = 0, LineNumber = 0, StackTrace = StackTrace { CallFrames = System.Collections.Generic.List`1[OpenQA.Selenium.BiDi.Modules.Script.StackFrame] }, Text = ReferenceError: boom is not defined }, Realm = OpenQA.Selenium.BiDi.Modules.Script.Realm }
```

Now just introduce nice `record formatting`: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#built-in-formatting-for-display

Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/EvaluateCommand.cs]: To improve further just define how `EvaluateResultException` should be represented to string (according the link above). I am going to merge this PR as important.

File: dotnet/src/webdriver/BiDi/Modules/Script/StackFrame.cs [hunk 6]
```diff
@@ -19,4 +19,15 @@
 
 namespace OpenQA.Selenium.BiDi.Modules.Script;
 
-public record StackFrame(long LineNumber, long ColumnNumber, string Url, string FunctionName);
+public record StackFrame(long LineNumber, long ColumnNumber, string Url, string FunctionName)
+{
+    public string FormatStackFrame()
```
Comment (nvborisenko) [inline dotnet/src/webdriver/BiDi/Modules/Script/StackFrame.cs]: Remove it.

File: dotnet/src/webdriver/BiDi/Modules/Script/StackTrace.cs [hunk 7]
```diff
@@ -17,8 +17,27 @@
...
+using System;
 using System.Collections.Generic;
+using System.Linq;
 
 namespace OpenQA.Selenium.BiDi.Modules.Script;
 
-public record StackTrace(IReadOnlyCollection<StackFrame> CallFrames);
+public record StackTrace(IReadOnlyList<StackFrame> CallFrames)
+{
+    public string FormatStackTrace(int indent)
```
Comment (nvborisenko) [inline dotnet/src/webdriver/BiDi/Modules/Script/StackTrace.cs]: Remove it.

File: dotnet/src/webdriver/BiDi/Modules/Script/StackFrame.cs (hunk 6 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/StackFrame.cs]: Done.

File: dotnet/src/webdriver/BiDi/Modules/Script/StackTrace.cs (hunk 7 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Modules/Script/StackTrace.cs]: Done.

**Review by nvborisenko — APPROVED** [review]
Thanks Mike.
