### PR TITLE
[grid] Silent fail on invalid log level

### LINKED ISSUE #15790: [🐛 Bug]: Hub fails to start with --log-level DEBUG
### Description

**Environment:**
- Selenium version: 4.33.0
- Java version: OpenJDK 17
- OS: macOS (Sonoma)

**Steps to reproduce:**
- `java -jar selenium-server-4.33.0.jar hub --log-level DEBUG`

**Expected Result:**
- Hub starts and logs appear at DEBUG level.

**Actual Result:**
- No output is shown.
- Hub process silently fails (no logs, no errors).
- Confirmed that `--log /dev/stdout` and `-verbose` show class loading but no actual boot logic.

**Workarounds**
- `--log-level INFO` works
- `--log-level FINE` works

I've tried older versions up to 4.15, none of them work with `--log-level DEBUG`, however there's a log message appearing with 4.15 - the log does not appear with any other version between 4.33 and 4.15:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: Unable to determine log level from DEBUG
	at org.openqa.selenium.grid.log.LoggingOptions.setLoggingLevel(LoggingOptions.java:79)
	at org.openqa.selenium.grid.log.LoggingOptions.configureLogging(LoggingOptions.java:115)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:120)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:56)
	at org.openqa.selenium.grid.Main.main(Main.java:41)
	... 6 more
```

### Reproducible Code

```shell
java -jar selenium-server-4.33.0.jar hub --log-level DEBUG
```

### Debugging Logs

```logs
No logs at all.
```

### PR DESCRIPTION
**Pull request by Oxilod**
### 🔗 Related Issues
Fixes #15790

### 💥 What does this PR do?
Fixing issue where providing an invalid log level to Grid will fail silently.

### 🔧 Implementation Notes
Since the logger is not yet configured a stacktrace with the exception is printed to console and we continue since the default log level is already configured.

I've considered percolating the exception up to the TemplateGrid.java, configure() method and doing a try catch there but to me it's unnecessarily complicated.

### 🔄 Types of changes
- Bug fix (backwards compatible)

___

### **PR Type**
Bug fix

___

### **Description**
- Print stacktrace when invalid log level is provided

- Prevent silent failure by notifying via console output

- Default log level is used if invalid value is given

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>LoggingOptions.java</strong><dd><code>Handle invalid log level with stacktrace and fallback</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/grid/log/LoggingOptions.java

<li>Catches invalid log level and prints stacktrace to console<br> <li> Continues with default log level instead of failing silently

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15796/files#diff-df04b67d453fdda127e86957b1cb29596a05a07e711f9081cfa4af5ed7094a1b">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

**Comment by cgoldberg** [comment]
@Oxilod Can you run the formatter against your branch to fix the CI failure?

`./scripts/format.sh`

File: java/src/org/openqa/selenium/grid/log/LoggingOptions.java [hunk 1]
```diff
@@ -76,7 +76,9 @@ public void setLoggingLevel() {
     try {
       level = Level.parse(configLevel.toUpperCase(Locale.ROOT));
     } catch (IllegalArgumentException e) {
-      throw new ConfigException("Unable to determine log level from " + configLevel);
+      // Logger is not configured yet
+      new ConfigException("Unable to determine log level from " + configLevel +
+       ". Using default " + DEFAULT_LOG_LEVEL).printStackTrace();
```
Comment (diemol) [inline java/src/org/openqa/selenium/grid/log/LoggingOptions.java]: Can you please add this link: https://docs.oracle.com/en/java/javase/11/docs/api/java.logging/java/util/logging/Level.html, which shows the valid levels.

**Review by diemol — CHANGES_REQUESTED** [review]

**Comment by Oxilod** [comment]
@cgoldberg Sorry for the formatting issue. I've fixed it by running the script and pushed the changes.

File: java/src/org/openqa/selenium/grid/log/LoggingOptions.java (hunk 1 above)
Comment (Oxilod) [reply java/src/org/openqa/selenium/grid/log/LoggingOptions.java]: @diemol Added to link for more clarity. Thanks for flagging this.

Comment (VietND96) [reply java/src/org/openqa/selenium/grid/log/LoggingOptions.java]: I am thinking can we print out all those ENUM values as strings in the message, instead of the link which might change in the future?

Comment (diemol) [reply java/src/org/openqa/selenium/grid/log/LoggingOptions.java]: Either way, we need to tell the user valid values.

Comment (Oxilod) [reply java/src/org/openqa/selenium/grid/log/LoggingOptions.java]: I gave it a try but I found no easy way of retrieving the log levels from `java.util.logging.Level`. It seems that `System.Logger.Level` is indeed an ENUM, however the values there seem to be different (https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.Logger.Level.html).

Let me know if I'm missing something.

**Comment by cgoldberg** [comment]
I think it would be fine to just hardcode the available levels in the error message. They aren't going to change over time

File: java/src/org/openqa/selenium/grid/log/LoggingOptions.java (hunk 1 above)
Comment (cgoldberg) [reply java/src/org/openqa/selenium/grid/log/LoggingOptions.java]: I think it would be fine to just hardcode the available levels in the error message. They aren't going to change over time.

Comment (Oxilod) [reply java/src/org/openqa/selenium/grid/log/LoggingOptions.java]: Done!

**Review by diemol — APPROVED** [review]

**Comment by diemol** [comment]
Thank you, @Oxilod!
