### PR TITLE
[cdp][java] Continue requests without modification for know errors in NetworkInterceptor

### LINKED ISSUE #13774: [🐛 Bug]: NetworkInterceptor overwrites failed requests with 200 response
### What happened?

I've been using `NetworkInterceptor` successfully with Chrome to add headers to requests. However, I've run into an edge case where `NetworkInterceptor` does the wrong thing.

If the request fails by not returning a response (e.g. there's a timeout or the hostname does not exist), Selenium replaces the response with a empty 200 response and returns that to Chrome. This causes Chrome to load an empty page rather than failing.

As you can see from the logs below, the second `Fetch.requestPaused` message from Chrome contains `"responseErrorReason":"NameNotResolved"`. After this Selenium sends an inappropriate `Fetch.getResponseBody`, which fails. Selenium constructs an empty 200 response and passes that back to the user's filter. Whatever that filter return is then sent via a `Fetch.fulfillRequest` call. As far as I can tell, there is no way for the user's filter to distinguish one of these fake 200 responses for a real 200 response (other than the fact that the response is otherwise empty).

I'm not entirely sure how Selenium should handle this error but sending a `Fetch.continueRequest` seems to make sense and makes the behaviour consistent to how Selenium behaves if the `NetworkInterceptor` has not been used. i.e. the web driver will throw a `WebDriverException` from `driver.get`.

The faulty logic seems to be in `v123Network#createSeMessages`. It checks to see if `responseErrorReason` is set but otherwise ignores the value, continuing on to try to fetch the response body. When that fails, it assumes the reason for such a failure is due to a redirect response, at which point an empty 200 response is constructed.

### How can we reproduce the issue?

```shell
WebDriver driver = ...
Filter filter = next -> next;
try (var ignored = new NetworkInterceptor(driver, filter)) {
  // This should raise an exception, but doesn't!
  driver.get("https://fakesite.pro/en/index.html");
  // The web browser has loaded an empty page, even though fakesite.pro doesn't exist.
}
```

### Relevant log output

```shell
2024-04-03T12:53:33.759-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : <- {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-1.0","request":{"url":"https://fakesite.pro/en/index.html","method":"GET","headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","Accept-Language":"en-GB,en-US;q=0.9,en;q=0.8","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"},"initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"618FD10968BEC9788FF3163BFDE85FAD","resourceType":"Document"},"sessionId":"F9C647A6D0F886EAE174C7CFD101EF46"}
2024-04-03T12:53:33.760-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : Method Fetch.requestPaused called with 2 callbacks available
2024-04-03T12:53:33.760-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : Matching Fetch.requestPaused with Fetch.requestPaused
2024-04-03T12:53:33.762-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : Calling callback for Fetch.requestPaused using org.openqa.selenium.devtools.idealized.Network$$Lambda/0x000000050184e7b8@34b31eb3 being passed org.openqa.selenium.devtools.v123.fetch.model.RequestPaused@14ca5f7b
2024-04-03T12:53:33.763-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : -> {
  "id": 7,
  "sessionId": "F9C647A6D0F886EAE174C7CFD101EF46",
  "method": "Fetch.continueRequest",
  "params": {
    "postData": "",
    "requestId": "interception-job-1.0",
    "method": "GET",
    "headers": [
      {
        "name": "Accept",
        "value": "text\u002fhtml,application\u002fxhtml+xml,application\u002fxml;q=0.9,image\u002favif,image\u002fwebp,image\u002fapng,*\u002f*;q=0.8,application\u002fsigned-exchange;v=b3;q=0.7"
      },
      {
        "name": "Upgrade-Insecure-Requests",
        "value": "1"
      },
      {
        "name": "User-Agent",
        "value": "Mozilla\u002f5.0 (X11; Linux x86_64) AppleWebKit\u002f537.36 (KHTML, like Gecko) Chrome\u002f123.0.0.0 Safari\u002f537.36"
      },
      {
        "name": "Accept-Language",
        "value": "en-GB,en-US;q=0.9,en;q=0.8"
      }
    ],
    "url": "https:\u002f\u002ffakesite.pro\u002fen\u002findex.html"
  }
}
2024-04-03T12:53:33.766-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : <- {"id":7,"result":{},"sessionId":"F9C647A6D0F886EAE174C7CFD101EF46"}
2024-04-03T12:53:33.777-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : <- {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-1.0","request":{"url":"https://fakesite.pro/en/index.html","method":"GET","headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","Accept-Language":"en-GB,en-US;q=0.9,en;q=0.8","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"},"initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"618FD10968BEC9788FF3163BFDE85FAD","resourceType":"Document","responseErrorReason":"NameNotResolved"},"sessionId":"F9C647A6D0F886EAE174C7CFD101EF46"}
2024-04-03T12:53:33.778-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : Method Fetch.requestPaused called with 2 callbacks available
2024-04-03T12:53:33.778-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : Matching Fetch.requestPaused with Fetch.requestPaused
2024-04-03T12:53:33.778-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : Calling callback for Fetch.requestPaused using org.openqa.selenium.devtools.idealized.Network$$Lambda/0x000000050184e7b8@34b31eb3 being passed org.openqa.selenium.devtools.v123.fetch.model.RequestPaused@744853f6
2024-04-03T12:53:33.779-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : -> {
  "id": 8,
  "sessionId": "F9C647A6D0F886EAE174C7CFD101EF46",
  "method": "Fetch.getResponseBody",
  "params": {
    "requestId": "interception-job-1.0"
  }
}
2024-04-03T12:53:33.781-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : <- {"id":8,"error":{"code":-32000,"message":"Can only get response body on requests captured after headers received."},"sessionId":"F9C647A6D0F886EAE174C7CFD101EF46"}
2024-04-03T12:53:33.782-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : Matching Fetch.requestPaused with Fetch.authRequired
2024-04-03T12:53:33.783-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : -> {
  "id": 9,
  "sessionId": "F9C647A6D0F886EAE174C7CFD101EF46",
  "method": "Fetch.fulfillRequest",
  "params": {
    "responseHeaders": [
    ],
    "body": "",
    "requestId": "interception-job-1.0",
    "responseCode": 200
  }
}
2024-04-03T12:53:33.785-04:00  INFO 33243 --- [ CDP Connection] o.openqa.selenium.devtools.Connection    : <- {"id":9,"result":{},"sessionId":"F9C647A6D0F886EAE174C7CFD101EF46"}
```

### Operating System

macOS Sonoma 14.4.1

### Selenium version

Java 4.19.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 123.0

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123.0

### Are you using Selenium Grid?

4.19.1

### PR DESCRIPTION
**Pull request by pujagani**
## **User description**
Related to #13774

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Selenium was returning an HTTP 200 response if CDP responded with an error parameter in the paused request. The changes fix this by adding a check and continuing the request without modification.

### Motivation and Context

Fixes #13774 

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

___

## **Type**
Bug fix, Enhancement

___

## **Description**
- Added error response handling in network request interception across multiple versions (v85, v121, v122, v123) to continue without modification when errors are detected.
- Enhanced the idealized network handling to improve the response to paused requests with errors.
- Updated tests to check the new behavior ensuring that requests with known errors are handled correctly.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Network.java</strong><dd><code>Enhance error handling in paused network requests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/devtools/idealized/Network.java

<li>Added a check for error responses in paused requests and continue <br>without modification if an error is present.<br> <li> Enhanced the handling of paused requests by directly continuing them <br>when an error response is detected.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13836/files#diff-e2eaccc33e555132eea5a90c621e9bc3f356dc3da108fa43ff0db0534946b4fd">+8/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>v121Network.java</strong><dd><code>Implement error response handling in v121</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/devtools/v121/v121Network.java

<li>Implemented method to check for error responses in paused requests.<br> <li> Adjusted logic to only consider response status code for creating <br>messages.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13836/files#diff-a5d6564d19b18aff33fea626ca28f1c734350c62f2a1b07dfe12f4b7d85eef60">+6/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>v122Network.java</strong><dd><code>Add error handling in network requests for v122</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/devtools/v122/v122Network.java

<li>Added method to detect error responses in network requests.<br> <li> Modified message creation to ignore error reasons unless a status code <br>is present.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13836/files#diff-07881f5d2a76a8bc4f996df0bce3df021793ee4c4c2eaf64ab76d9978791889f">+6/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>v123Network.java</strong><dd><code>Introduce error response handling in v123</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/devtools/v123/v123Network.java

<li>Introduced error response detection for paused network requests.<br> <li> Altered message creation logic to focus on status codes.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13836/files#diff-a13835552724f8a6dc3631aee2e77d61a711deae7f335bb9248f5fd0f5a8ad98">+6/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>V85Network.java</strong><dd><code>Simplify and enhance error handling in V85 network interception</code></dd></summary>
<hr>
      
java/src/org/openqa/selenium/devtools/v85/V85Network.java

<li>Added error response detection in network interception.<br> <li> Simplified message creation by focusing on status codes.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13836/files#diff-7d2ede887b6d41abf418cc653aad842cdf24ae4fc6b61ffacb204ee63dc91f88">+6/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>NetworkInterceptorTest.java</strong><dd><code>Update tests for new error handling in network requests</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
java/test/org/openqa/selenium/devtools/NetworkInterceptorTest.java

<li>Added a test to ensure proper handling when a known error occurs <br>during a network request.<br> <li> Modified existing tests to adapt to the new error handling mechanism.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13836/files#diff-3a210ca03f8e29c8097e6d7f9d056db7a17335a669c61a64e60e37f2158733d9">+14/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

File: java/src/org/openqa/selenium/devtools/idealized/Network.java [hunk 1]
```diff
@@ -200,6 +200,12 @@ public void prepareToInterceptTraffic() {
         pausedRequest -> {
           try {
             String id = getRequestId(pausedRequest);
+
+            if (hasErrorResponse(pausedRequest)) {
+              devTools.send(continueWithoutModification(pausedRequest));
```
Comment (joebandenburg) [inline java/src/org/openqa/selenium/devtools/idealized/Network.java:206]: Do we need to clean up the future in pendingResponses for this interception?

Comment (pujagani) [reply java/src/org/openqa/selenium/devtools/idealized/Network.java:206]: Yes, you are right. I have updated the PR for the same.
