### PR TITLE
[rust] Fix proxy setup in Selenium Manager (fix #12104)

### LINKED ISSUE #12104: [🐛 Bug]: Selenium Manager Proxy Not Working
### What happened?

As of #11865 the proxy value is being ignored

### How can we reproduce the issue?

```shell
./selenium-manager --browser chrome --proxy http://localhost:8080
```
this should return:
```
ERROR   error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_113): error trying to connect: tcp connect error: Connection refused (os error 61)
```

### Relevant log output

```shell
$ ./selenium-manager --browser chrome --proxy http://localhost:8080 --debug
DEBUG	Using proxy: http://localhost:8080
DEBUG	Using shell command to find out chrome version
DEBUG	Running command: "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --version"
DEBUG	Output: "Google Chrome 113.0.5672.126 "
DEBUG	The version of chrome is 113.0.5672.126
DEBUG	Detected browser: chrome 113
DEBUG	Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_113
DEBUG	Required driver: chromedriver 113.0.5672.63
DEBUG	Running command: "chromedriver --version"
DEBUG	Output: ""
DEBUG	Driver URL: https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_mac64.zip
DEBUG	File extracted to /Users/titusfortner/.cache/selenium/chromedriver/mac64/113.0.5672.63/chromedriver (17875584 bytes)
INFO	/Users/titusfortner/.cache/selenium/chromedriver/mac64/113.0.5672.63/chromedriver
```

### Operating System

macOS

### Selenium version

n/a

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

### PR DESCRIPTION
**Pull request by bonigarcia**
### Description
This PR fixes the proxy setup in Selenium Manager, broken as of #11865. Also, this PR contains a negative test for proxy setup.

UPDATE: I discovered the existing proxy test based on mockserver was actually not working, so I dropped that test in this PR. To test manually the proxy support, I used [mitmproxy](https://mitmproxy.org/) locally, but I haven't found a manner to implement an automated test about it. 

### Motivation and Context
This PR fixes #12104.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by oriongonza** [comment]
What was the issue? I think I messed up when merging

**Comment by bonigarcia** [comment]
> What was the issue? I think I messed up when merging

This [change](https://github.com/SeleniumHQ/selenium/pull/11865/files#diff-f64796ccc388f201986ea7eaaf07bbefbd8ac1a56bb995fb505da80879872a39R521) broke the proxy support. The current PR should fix it.

File: rust/tests/proxy_tests.rs [hunk 1]
```diff
@@ -19,16 +19,19 @@ use assert_cmd::Command;
 
 use exitcode::DATAERR;
 
-use wiremock::MockServer;
-
 #[tokio::test]
-async fn ok_proxy_test() {
```
Comment (diemol) [inline rust/tests/proxy_tests.rs:25]: Why not have both ok and wrong tests?

Comment (bonigarcia) [reply rust/tests/proxy_tests.rs:25]: I removed that test in a second commit since I discovered that test was actually not working. When it passed, it did since the driver was cached, but the mocked proxy was not actually doing anything. In fact, if the flag `--clear-cache` is added the test, the test always fails. I looked for an alternative mocked proxy in Rust but I haven't found anything. So I decided to drop the test. I added an update in the original PR description to inform about it.

Comment (diemol) [reply rust/tests/proxy_tests.rs:25]: Makes sense.

**Review by diemol — APPROVED** [review]
Thank you, @bonigarcia!
