### PR TITLE
[java] fix bug for appium subclass that sets neither log file nor out…

### LINKED ISSUE #2004: null pointer exception from remote DriverService class when  outputstream or logfile are not passed.
https://github.com/appium/java-client/blob/2fd8c0cadce1a97a8a73e6ede893499f3d80414b/src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java#L92C32-L92C32

java.lang.NullPointerException
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:228)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.openqa.selenium.remote.service.DriverService$Builder.getLogOutput(DriverService.java:448)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:495)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:92)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildDefaultService(AppiumDriverLocalService.java:88)

### PR DESCRIPTION
**Pull request by titusfortner**
…put stream

### Description
Allow subclasses not to set either log file or log output

### Motivation and Context
Fix https://github.com/appium/java-client/issues/2004

### CODE REVIEW

**Review by diemol — APPROVED** [review]

**Review by valfirst — APPROVED** [review]

File: java/src/org/openqa/selenium/remote/service/DriverService.java [hunk 1]
```diff
@@ -445,7 +445,13 @@ protected Duration getDefaultTimeout() {
...
+        if (logOutputStream == null && getLogFile() == null) {
+          return ByteStreams.nullOutputStream();
+        } else if (logOutputStream == null) {
+          return new FileOutputStream(getLogFile());
+        } else {
+          return logOutputStream;
+        }
       } catch (FileNotFoundException e) {
         throw new RuntimeException(e);
       }
```
Comment (valfirst) [inline java/src/org/openqa/selenium/remote/service/DriverService.java]:
```java
        protected OutputStream getLogOutput() {
            if (logOutputStream != null) {
                return logOutputStream;
            }
            try {
                File logFile = getLogFile();
                return logFile == null ? ByteStreams.nullOutputStream() : new FileOutputStream(logFile);
            } catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            }
        }
```
?

Comment (titusfortner) [reply java/src/org/openqa/selenium/remote/service/DriverService.java]: Yes, that's better code.
