### PR TITLE
Fixes #2888 - Retry on network error

### LINKED ISSUE #2888: Occasional EADDRINUSE by chromedriver causes crash
## Meta -

OS:  Windows 10
Selenium Version:  3.0.0-beta-2 (NodeJS)
Browser:  Chrome
Browser Version:  53.0.2785.116 (Official Build) m (32-bit)
## Expected Behavior -

Attempt to resolve connection if possible, or at least allow users to provide their own error handler.
## Actual Behavior -

Unsure if this is a chromedriver issue, selenium webdriver issue or an operator issue. Occasionally during a portion of my tests where I conduct a fair bit of waiting in the form:

```
// Wait up to 10 seconds for the control to appear
driver.wait(Until.elementLocated(By.xpath('/html/body/div[4]/div/div[2]/div/div[2]/div[1]')), 10000).then(function(element) {
    expect(element).to.not.be.null;

    // Wait up to 10 seconds for the control to disappear
    driver.wait(Until.elementIsNotVisible(element), 10000).then(function(element) {
        done();
    });
});
```

I receive an error from https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/http/index.js#L238.

Without having delved into the actual implementation, I assume that this code, under the hood, will open many repeat connections to the chromedriver in order to poll for element state. After a while, this eventually causes an `EADDRINUSE` error to be thrown by the above linked error handler, causing the webdriver to stop. This issue does not happen when using firefox. Error in question:

```
Uncaught Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:57941                                                                                                                            
      at ClientRequest.<anonymous> (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\http\index.js:238:15)                                           
      at Socket.socketErrorListener (_http_client.js:308:9)                                                                                                                                   
      at emitErrorNT (net.js:1272:8)                                                                                                                                                          
      at _combinedTickCallback (internal/process/next_tick.js:74:11)                                                                                                                          
      at process._tickCallback (internal/process/next_tick.js:98:9)                                                                                                                           
  From: Task: WebElement.getTagName()                                                                                                                                                         
      at Driver.schedule (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\webdriver.js:414:17)                                                  
      at WebElement.schedule_ (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\webdriver.js:1820:25)                                            
      at WebElement.getTagName (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\webdriver.js:2012:17)                                           
      at d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\until.js:282:20                                                                        
      at d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\webdriver.js:753:14                                                                    
      at TaskQueue.execute_ (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2736:14)                                                
      at TaskQueue.executeNext_ (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2719:21)                                            
      at asyncRun (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2642:25)                                                          
      at d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:639:7                                                                       
  From: Task: <anonymous>                                                                                                                                                                     
      at Timeout.pollCondition [as _onTimeout] (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2178:16)                             
  From: Task: Waiting element to become stale                                                                                                                                                 
      at ControlFlow.wait (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2171:17)                                                  
      at Driver.wait (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\webdriver.js:749:29)                                                      
      at d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\spec\setup\products\productDetails.spec.js:28:28                                                                           
      at ManagedPromise.invokeCallback_ (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:1315:14)                                    
      at TaskQueue.execute_ (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2736:14)                                                
      at TaskQueue.executeNext_ (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2719:21)                                            
      at asyncRun (d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:2595:27)                                                          
      at d:\SVN\<redacted>\Testing\trunk\GUITesting\Selenium\node_modules\selenium-webdriver\lib\promise.js:639:7                                           
```

I fixed this issue locally by replacing above error handler with:

```
request.on('error', function(e) {
  if (e.code === 'ECONNRESET' || e.code === 'EADDRINUSE') {
    setTimeout(function() {
      sendRequest(options, onOk, onError, opt_data, opt_proxy);
    }, e.code === 'EADDRINUSE' ? 50 : 15);
  } else {
    var message = e.message;
    if (e.code) {
      message = e.code + ' ' + message;
    }
    onError(new Error(message));
  }
});
```

This works fine. If you add a console log above for each retry it retries maybe 5-10 times before it starts working again. This makes me think that the issue is with clogging up the communications (`netstat -a` shows the ports hitting 65535 with requests to the what I can only assume is the chromedriver).

I have tried running chromedriver in verbose mode with logging turned on, there are no events being displayed from within chromedriver to indicate that it is failing.

If this is an issue with chromedriver instead of webdriver please close this and I will see what they have to say on the issue.
## Steps to reproduce -

Can't easily provide as the point at which this occurs is variable, however it always happens inside tests with the above wait-based code.

### PR DESCRIPTION
**Pull request by seanpoulter**
Unlike the Ruby bindings, the JavaScript selenium-webdriver `sendRequest()` call did not retry on EADDRINUSE or ECONNABORTED network errors. This seems to affect Windows users who haven't  increased the number of ephemeral ports more often that others. The JS has been updated to behave the same as the Ruby **except** the timeout was kept as 15 ms instead of 2s. While 15 ms seems a bit too fast, 2s seems like an eternity to introduce into a test.

This doesn't have tests (yet) -- I can't get the tests to even start using `go debug-start`. It should be a quick with the teams favorite `http`/`https` mock.

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

File: javascript/node/selenium-webdriver/http/index.js [hunk 1]
```diff
@@ -144,8 +144,9 @@ class HttpClient {
  * @param {function(!Error)} onError The function to call if the request fails.
  * @param {?string=} opt_data The data to send with the request.
  * @param {?RequestOptions=} opt_proxy The proxy server to use for the request.
+ * @param {!number=} retries The current number of retries.
```
Comment (jleyba) [inline javascript/node/selenium-webdriver/http/index.js]: !numbers -> numbers

File: javascript/node/selenium-webdriver/http/index.js [hunk 2]
```diff
@@ -144,8 +144,9 @@ class HttpClient {
...
  */
-function sendRequest(options, onOk, onError, opt_data, opt_proxy) {
+function sendRequest(options, onOk, onError, opt_data, opt_proxy, retries) {
```
Comment (jleyba) [inline javascript/node/selenium-webdriver/http/index.js]: please be consistent with naming: `opt_retries`

File: javascript/node/selenium-webdriver/http/index.js [hunk 3]
```diff
@@ -247,6 +253,36 @@ function sendRequest(options, onOk, onError, opt_data, opt_proxy) {
...
+ * @param {!Error} err
+ * @return {!boolean}
+ */
+function shouldRetryRequest(retries, err) {
+  return retries < MAX_RETRIES && isRetryableNetworkError(err);
+}
+
+/**
+ * @param {!Error} err
+ * @return {!boolean}
```
Comment (jleyba) [inline javascript/node/selenium-webdriver/http/index.js]: just `boolean`

File: javascript/node/selenium-webdriver/http/index.js [hunk 4]
```diff
@@ -247,6 +253,36 @@ function sendRequest(options, onOk, onError, opt_data, opt_proxy) {
...
+const MAX_RETRIES = 3;
+
+/**
+ * A retry is sometimes needed on Windows where we may quickly run out of
+ * ephemeral ports. A more robust solution is bumping the MaxUserPort setting
+ * as described here: http://msdn.microsoft.com/en-us/library/aa560610%28v=bts.20%29.aspx
+ *
+ * @param {!number} retries
+ * @param {!Error} err
+ * @return {!boolean}
```
Comment (jleyba) [inline javascript/node/selenium-webdriver/http/index.js]: just `boolean`

**Comment by seanpoulter** [comment]
Sorry for mixing up those type annotations Jason. Should be good.

**Comment by cgoldberg** [comment]
Those socket errors can be caused by other conditions than port exhaustion. I'm not sure retrying is always appropriate for ECONNABORTED/ECONNRESET/EADDRINUSE.

**Comment by seanpoulter** [comment]
What cases are you thinking of Corey? This is the same behavior as the Ruby bindings. Are there design docs to refer to for what was already decided and the reasoning behind it?

**Comment by cgoldberg** [comment]
@seanpoulter 

> This is the same behavior as the Ruby bindings

That doesn't make it correct, and other language bindings behave differently.

> Are there design docs to refer to for what was 
> already decided and the reasoning behind it?

yea right :)

my $.02 is that if you are getting network errors like described, it should just fail quickly instead of retrying for 45 secs before failing.

**Comment by seanpoulter** [comment]
Is it worth laying out the groundwork for a design review across the bindings?

To clarify, this change introduces a worst case 45 ms delay from the `setTimeout` calls and the time in flight.
