### PR TITLE
[java] Fix Unicode value for OPTION key in Keys enum

### LINKED ISSUE #15945: [🚀 Feature]: Add macOS-specific keys (OPTION, FN) to Keys enum
### Description

I didn't walk through implementation details, but seems https://github.com/SeleniumHQ/selenium/pull/15910 is beneficial for all bindings.

### Have you considered any alternatives or workarounds?

https://github.com/SeleniumHQ/selenium/pull/15910

### PR DESCRIPTION
**Pull request by iampopovich**
### 🔗 Related Issues
fixes #15945 also fixes #15910

### 💥 What does this PR do?
Option key code fixed according to specification https://w3c.github.io/webdriver/#keyboard-actions

### 🔧 Implementation Notes
This pull request includes a small change to the `Keys` enum in the `Keys.java` file. The change updates the Unicode value for the `OPTION` key to align with the WebDriver specification.

### 🔄 Types of changes

- Bug fix (backwards compatible)
- New feature (non-breaking change which adds functionality *and tests!*)

___

### **PR Type**
Bug fix

___

### **Description**
- Fix Unicode value for OPTION key in Keys enum

- Update from '\uE050' to '\uE052' to align with WebDriver specification

- Resolves macOS keyboard action compatibility issues

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Keys.java</strong><dd><code>Fix OPTION key Unicode value</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/Keys.java

<li>Changed OPTION key Unicode value from '\uE050' to '\uE052'<br> <li> Updated to align with WebDriver specification for keyboard actions

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15966/files#diff-5f8d999411bc04e9f2894a56fc2b1212bd5511074a19731f7e2025875e5626b1">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

File: java/src/org/openqa/selenium/Keys.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ public enum Keys implements CharSequence {
   RIGHT_COMMAND('\uE053'),
 
   // Symbolic macOS keys not yet standardized
-  OPTION('\uE050'), // TODO: verify Unicode value with WebDriver spec
+  OPTION('\uE052'), // TODO: verify Unicode value with WebDriver spec
```
Comment (Delta456) [inline java/src/org/openqa/selenium/Keys.java]:
```suggestion
  OPTION('\uE052'), 
```

As this PR verifies it is correct
