### PR TITLE
[grid] Accommodate ability to specify sub-paths

### LINKED ISSUE #10847: [🚀 Feature]: Subpath parameter for subpath ingress configurations
### Feature and motivation

Adding parameter for subpath configuration so inside container application can work on different path than root.

I've tested rewrite rules on ingress and they do not work correctly.

### Usage example

Currently application works on http://localhost:4444 inside of the container, unfortunately in ingress implementation with reverse-proxy application will not respond correctly to ingress configuration where path is configured different than "/"
New parameter would allow to change base URL of the application to work on http://localhost/selenium:4444 which will allow correct communication with ingress.

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes: #10847

Sub-paths can now be specified for the below 
Components:
1. Hub
2. Standalone
3. Router

It can be specified via `--sub-path <actualPathGoesHere>`

Or via the Toml configuration file by specifying

```yaml
[reverse_proxy]
sub-path = “<actualPathGoesHere>”
```

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Sub-paths can now be specified for the below 
Components:
1. Hub
2. Standalone
3. Router

It can be specified via “--sub-path <actualPathGoesHere>”

Or via the Toml configuration file by specifying

[reverse_proxy]
sub-path = “<actualPathGoesHere>”

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@diemol - I have only run `bazel test --cache_test_results=no java/test/org/openqa/selenium/grid/router:medium-tests`

File: java/src/org/openqa/selenium/grid/server/ReverseProxyFlags.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    names = {"--sub-path"},
+    arity = 1,
+    description = "A sub-path that should be considered for all user facing routes on the Hub/Router/Standalone")
+  @ConfigValue(section = REVERSE_PROXY_SECTION, name = "sub-path", example = "my_company/selenium_grid")
+  public String subPath;
+
+  @Override
+  public Set<Role> getRoles() {
+    return Collections.singleton(ROUTER_ROLE);
+  }
```
Comment (diemol) [inline java/src/org/openqa/selenium/grid/server/ReverseProxyFlags.java]: This can be part of the `RouterFlags`, no need for a new class.

File: java/src/org/openqa/selenium/grid/server/ReverseProxyOptions.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+      prefix = prefix.trim();
+      if (!prefix.startsWith("/")) {
+        prefix = "/" + prefix; //Prefix with a '/' if absent.
+      }
+      if (prefix.endsWith("/")) {
+        prefix = prefix.substring(0, prefix.length() -1); //Remove the trailing '/' if present.
+      }
+      return prefix;
+    }).orElse("");
+  }
```
Comment (diemol) [inline java/src/org/openqa/selenium/grid/server/ReverseProxyOptions.java]: You can create this as the `RouterOptions` if you wish.

File: java/src/org/openqa/selenium/grid/web/GridUiRoute.java [hunk 3]
```diff
@@ -65,4 +77,34 @@ public boolean matches(HttpRequest req) {
...
+    };
+  }
+
+  private static Routable[] redirectRoutes(String prefix, Supplier<HttpHandler> handler ) {
+    if (prefix.isEmpty()) {
+      return new Routable[]{};
+    }
+    prefix = prefix.endsWith("/") ? prefix.substring(0, prefix.length() -1) : prefix;
+    return new Routable[]{get(prefix).to(handler)};
+  }
```
Comment (diemol) [inline java/src/org/openqa/selenium/grid/web/GridUiRoute.java]: This could be a single method by adding a 3rd parameter, which is the route itself, right?

**Review by diemol — CHANGES_REQUESTED** [review]
Thank you, @krmahadevan!

Left some comments so we can iterate.

File: java/src/org/openqa/selenium/grid/web/GridUiRoute.java (hunk 3 above)
Comment (krmahadevan) [reply java/src/org/openqa/selenium/grid/web/GridUiRoute.java]: I didn't quite understand this recommendation @diemol Can you please help elaborate? These 3 methods are adding different types of routes. Earlier they were 3 individual lines doing that, but now since we need to handle the prefix as well, i extracted them out as 3 specific methods.

File: java/src/org/openqa/selenium/grid/server/ReverseProxyFlags.java (hunk 1 above)
Comment (krmahadevan) [reply java/src/org/openqa/selenium/grid/server/ReverseProxyFlags.java]: Doing this would basically mean that I would need to alter dependencies because it looks like both `Hub` and `Standalone` don't have this package exposed to them via bazel. Is that fine @diemol

Comment (krmahadevan) [reply java/src/org/openqa/selenium/grid/server/ReverseProxyFlags.java]: Am seeing this when running the medium-tests from command line

```
# Execution platform: @local_config_platform//:host
java/src/org/openqa/selenium/grid/commands/Hub.java:44: error: package org.openqa.selenium.grid.router.httpd does not exist
import org.openqa.selenium.grid.router.httpd.RouterOptions;
```

I guess bazel is not happy here ?

Comment (krmahadevan) [reply java/src/org/openqa/selenium/grid/server/ReverseProxyFlags.java]: Please ignore this. Figured out what needs to be done.

File: java/src/org/openqa/selenium/grid/web/GridUiRoute.java (hunk 3 above)
Comment (diemol) [reply java/src/org/openqa/selenium/grid/web/GridUiRoute.java]: But aren't these three methods doing almost the same? Just with different values for the Route?

Comment (krmahadevan) [reply java/src/org/openqa/selenium/grid/web/GridUiRoute.java]: * `uiRoutes()` works with `Route.prefix()`
* `consoleRoutes()` works with `Route.get()`
* `redirectRoutes()` is applicable only if there was a prefix that was specified.

Unifying them would basically mean that we create one method which internally does all these 3 activities. It would be the same as having 3 explicit methods which explicitly clarify their intent.

Comment (krmahadevan) [reply java/src/org/openqa/selenium/grid/web/GridUiRoute.java]: Please check now. I have refactored it and simplified the logic a bit more.

**Comment by yashcho** [comment]
Any update @diemol ?

File: java/src/org/openqa/selenium/grid/router/httpd/RouterOptions.java [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+// specific language governing permissions and limitations
+// under the License.
+
+package org.openqa.selenium.grid.router.httpd;
+
+import org.openqa.selenium.grid.config.Config;
+
+public class RouterOptions {
+
+  static final String REVERSE_PROXY_SECTION = "reverse_proxy";
```
Comment (diemol) [inline java/src/org/openqa/selenium/grid/router/httpd/RouterOptions.java]: This can be called `NETWORK_SECTION`, naming it reverse proxy makes it very specific. It would then go together with the `relaxChecks` option already present in the `RouterFlags`.

**Review by diemol — CHANGES_REQUESTED** [review]
Thank you, @krmahadevan! Just a minor change requested from my side.

File: java/src/org/openqa/selenium/grid/router/httpd/RouterOptions.java (hunk 4 above)
Comment (krmahadevan) [reply java/src/org/openqa/selenium/grid/router/httpd/RouterOptions.java]: @diemol - I didn't understand this part. 

Are you suggesting something like this ? 

```java
static final String NETWORK_SECTION = "network";
```

Comment (diemol) [reply java/src/org/openqa/selenium/grid/router/httpd/RouterOptions.java]: Yes

**Comment by krmahadevan** [comment]
@diemol - I have addressed the last review comment, rebased off of trunk and force pushed this branch. Please take a look. I will send a separate PR for this for addressing the documentation needs.

**Review by diemol — APPROVED** [review]
Thank you, @krmahadevan!

**Comment by yashcho** [comment]
@diemol / @krmahadevan any idea in which release is it planned to rollout?

**Comment by titusfortner** [comment]
Should be available in 4.8 (the latest release)

**Comment by yashcho** [comment]
Thank you @titusfortner for information but I don't see it in release notes, even any idea on how it will work for docker-selenium?

**Comment by diemol** [comment]
I will publish the release blog post today. What is missing is the documentation for this feature in the docs.

**Comment by yashcho** [comment]
Thank you @diemol as I didn't work completely on creating this feature it would be difficult for me to write docs.

**Comment by diemol** [comment]
Apologies if my comment was ambiguous, @yashcho. I meant, we at Selenium need to document the feature.

**Comment by yashcho** [comment]
Understood, I would wait for the release note and feature doc.. :-)
