### PR TITLE
[dotnet] Fix logging issue when log context level conflicts with logger already captured level

### LINKED ISSUE #13839: [🐛 Bug]: .NET LogFileHandler not writing any logs
### What happened?

I want to use the FileLogHandler to write out driver logs to the filesystem. When I try this I see the log file gets created on disc but nothing is ever written to it.

### How can we reproduce the issue?

```shell
private const string LogFilePath = "C:\\Users\\MyName\\Downloads\\Gubbins\\logs.log";

[Test]
public async Task Test1()
{
    EdgeOptions edgeOptions = new();
    edgeOptions.AddArgument("--start-maximized");
    edgeOptions.AddArgument("--disable-dev-shm-usage");
    var driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), edgeOptions.ToCapabilities(), TimeSpan.FromSeconds(30));

    using (var logContext = Log.CreateContext(LogEventLevel.Trace).Handlers.Add(new FileLogHandler(LogFilePath)))
    {
        driver.Navigate().GoToUrl("https://www.google.co.uk");
        driver.Quit();
    }
}
```

### Relevant log output

```shell
I wish I could
```

### Operating System

Windows 10

### Selenium version

4.19.0

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

### Are you using Selenium Grid?

I am: 4.18.0-20240220

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
In general each `ILogger` should be copied to `LogContext`.

### Motivation and Context
Fixes https://github.com/SeleniumHQ/selenium/issues/13839

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Fixed log level handling in `LogContext` to ensure proper logging.

- Added logic to initialize loggers with the correct level in `LogContext`.

- Introduced new tests to validate logging behavior and context-specific log levels.

- Ensured global log state reset in test setup and teardown.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>LogContext.cs</strong><dd><code>Fix logger level handling in `LogContext`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/src/webdriver/Internal/Logging/LogContext.cs

<li>Adjusted <code>LogContext</code> to initialize loggers with correct levels.<br> <li> Fixed <code>IsEnabled</code> method to check logger levels accurately.<br> <li> Improved logger initialization to respect context-specific levels.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15057/files#diff-09e55ca02fe7a68ac190114b4bcbe9bc5f68d0b641f226bd17ffaf2a81d465b9">+5/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>LogTest.cs</strong><dd><code>Add tests for logging context behavior</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/test/common/Internal/Logging/LogTest.cs

<li>Added test to validate message emission in logging contexts.<br> <li> Reset global log state in test setup and teardown.<br> <li> Enhanced test coverage for context-specific log levels.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15057/files#diff-f381b4f23cf8f01f4d38e1bc82aeb949e4815570931aaa2e68dda7b358ef3799">+24/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

File: dotnet/test/common/Internal/Logging/LogTest.cs [hunk 1]
```diff
@@ -28,13 +28,27 @@ public class LogTest
         private TestLogHandler testLogHandler;
         private ILogger logger;
 
+        private void ResetGlobalLog()
```
Comment (RenderMichael) [inline dotnet/test/common/Internal/Logging/LogTest.cs:31]: Should this functionality be available on `Log` directly?

Comment (nvborisenko) [reply dotnet/test/common/Internal/Logging/LogTest.cs:31]: Less functionality is better, especially for logging in Selenium :)

File: dotnet/src/webdriver/Internal/Logging/LogContext.cs [hunk 2]
```diff
@@ -98,7 +101,7 @@ public ILogger GetLogger(Type type)
 
         public bool IsEnabled(ILogger logger, LogEventLevel level)
         {
-            return Handlers != null && level >= _level && level >= logger.Level;
+            return Handlers != null && level >= _level && level >= _loggers?[logger.Issuer]?.Level;
```
Comment (nvborisenko) [inline dotnet/src/webdriver/Internal/Logging/LogContext.cs]: Should be `TryGet(...)` ?

File: dotnet/src/webdriver/Internal/Logging/LogContext.cs [hunk 3]
```diff
@@ -46,7 +46,10 @@ public LogContext(LogEventLevel level, ILogContext? parentLogContext, Concurrent
 
             _parentLogContext = parentLogContext;
 
-            _loggers = loggers;
+            if (loggers is not null)
+            {
+                _loggers = new ConcurrentDictionary<Type, ILogger>(loggers.Select(l => new KeyValuePair<Type, ILogger>(l.Key, new Logger(l.Value.Issuer, level))));
```
Comment (RenderMichael) [inline dotnet/src/webdriver/Internal/Logging/LogContext.cs]: This conversion is very complex and hard to follow. Since it is a clone of what is below, can we make a method?

```csharp
[return: NotNullIfNotNull(nameof(loggerMap))]
private static ConcurrentDictionary<Type, ILogger>? CloneWithMinimumLevel(ConcurrentDictionary<Type, ILogger>? loggerMap, LogEventLevel minimumLevel)
{
    if (loggerMap is null)
    {
        return null;
    }

    var cloned = new Dictionary<Type, ILogger>(loggerMap.Count);
    foreach (KeyValuePair<Type, ILogger> loggerKvp in loggerMap)
    {
        var clonedLogger = new Logger(loggerKvp.Value.Issuer, minimumLevel);
        cloned.Add(loggerKvp.Key, clonedLogger);

    }

    return new ConcurrentDictionary<Type, ILogger>(cloned);
}
```

Comment (nvborisenko) [reply dotnet/src/webdriver/Internal/Logging/LogContext.cs]: Makes sense.

File: dotnet/src/webdriver/Internal/Logging/LogContext.cs [hunk 4]
```diff
@@ -155,5 +156,24 @@ public void Dispose()
 
             Log.CurrentContext = _parentLogContext;
         }
+
+        [return: NotNullIfNotNull(nameof(loggers))]
+        private static ConcurrentDictionary<Type, ILogger>? CloneLoggers(ConcurrentDictionary<Type, ILogger>? loggers, LogEventLevel minimumLevel)
```
Comment (RenderMichael) [inline dotnet/src/webdriver/Internal/Logging/LogContext.cs:156]: Can you use this method on line 73 too?

Comment (nvborisenko) [reply dotnet/src/webdriver/Internal/Logging/LogContext.cs:156]: Absolutely! Done.
