### PR TITLE
[dotnet] [bidi] Properly return shared buffer when disposing websocket

### LINKED ISSUE #16801: [🐛 Bug]: .NET JSON parsing failures with Selenium.WebDriver 4.39.0 (taking screenshots and in custom app)
### Description

After updating `Selenium.WebDriver` from 4.38.0 to 4.39.0 in my .NET 8 ASP.NET Core web app's UI tests, I experience JSON parsing, with `Sytem.Text.Json`, starting to fail both in my app in various places (independent of Selenium), and in Selenium itself (when taking screenshots). The errors hint on the JSON files being corrupted, or that the app is not reading the JSON files it should (and could read without issues with 4.38.0). E.g.

```
OrchardCore.Setup.Services.SetupService: Unable to import a recipe during setup.System.Text.Json.JsonReaderException: '0x00' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
```

This isn't Selenium code, so I have no idea why it's affected (it does run in the [same process](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-8.0&pivots=xunit), though, so things like static member values are shared).

But I also sometimes get JSON exceptions from Selenium itself:

```
System.Text.Json.JsonReaderException: 'm' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 0 | BytePositionInLine: 147346.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
   at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at OpenQA.Selenium.Response.FromJson(String value)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(HttpResponseInfo responseInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.ExecuteAsync(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.ExecuteAsync(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.GetScreenshot()
   at Lombiq.Tests.UI.Extensions.ScreenshotUITestContextExtensions.TakeScreenshot(UITestContext context) in 
```

Note that this doesn't seem to happen on my Windows 11 desktop, but does when the UI tests are executed from GitHub Actions, both under Ubuntu 24.04 and Windows Server 2025. Also note that this is "random": while it does reliably fail all my CI test runs, it doesn't always happen at the same place (though that might be an artifact of different runs completing tests in slightly different order due to some jitter in speed).

Some other user [on Slack](https://seleniumhq.slack.com/archives/C0ABCS03F/p1765879112860629) has a screenshot image loading issue, what I think is actually the same problem, just manifesting at a later stage.

I first brought this up [on Slack](https://seleniumhq.slack.com/archives/C0ABCS03F/p1766871796995219) but was told to come here.

### Reproducible Code

```shell
// I don't have a proper one. The below code does NOT produce the error on my Windows 11 desktop
// (what doesn't exhibit it anyway, see above). I'm still trying to figure out how to reduce the massive
// framework, that uses frameworks behind the scenes, to a relevant code snippet.

using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

var chromeOptions = new ChromeOptions();
chromeOptions.BrowserVersion = "143.0.7499.169";
chromeOptions.AddArgument("--headless");

using var driver = new ChromeDriver(chromeOptions);

try
{
    driver.Navigate().GoToUrl("https://example.com");

    var screenshot = ((ITakesScreenshot)driver).GetScreenshot();
    var screenshotPath = Path.Combine(Directory.GetCurrentDirectory(), "screenshot.png");
    screenshot.SaveAsFile(screenshotPath);

    Console.WriteLine($"Screenshot saved to: {screenshotPath}");
}
finally
{
    driver.Quit();
}

Console.WriteLine("Done!");
```

---
ℹ️ **Last known working version:** `4.38.0`

### PR DESCRIPTION
**Pull request by nvborisenko**
### 🔗 Related Issues
Fixes #16801 

### 💥 What does this PR do?
Introduces `Dispose(bool disposing)` method to make sure shared buffer returned back to the pool only once.

### 🔄 Types of changes

- Bug fix (backwards compatible)

___

### **PR Type**
Bug fix

___

### **Description**
- Implements proper IDisposable pattern with Dispose(bool) method

- Ensures shared buffer returned to pool only once during disposal

- Prevents double-disposal of managed resources

- Seals class and nullifies buffer reference after return

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["WebSocketTransport"] -->|"implements"| B["IDisposable pattern"]
  B -->|"Dispose method"| C["calls Dispose(bool)"]
  C -->|"disposing=true"| D["dispose managed resources"]
  C -->|"disposing=false"| E["skip managed resources"]
  D -->|"then"| F["return buffer to pool once"]
  E -->|"then"| F
  F -->|"nullify buffer"| G["prevent double-return"]
```

<details><summary><h3>File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>WebSocketTransport.cs</strong><dd><code>Implement standard IDisposable pattern with proper cleanup</code></dd></summary>
<hr>

dotnet/src/webdriver/BiDi/WebSocketTransport.cs

<ul><li>Changed class from unsealed to sealed to prevent inheritance issues<br> <li> Changed <code>_receiveBuffer</code> from readonly to mutable field to allow <br>nullification<br> <li> Refactored Dispose() to call new Dispose(bool disposing) method with <br>GC.SuppressFinalize()<br> <li> Implemented Dispose(bool disposing) pattern to separate managed and <br>unmanaged resource cleanup<br> <li> Moved buffer return logic to Dispose(bool) and nullified buffer after <br>return to prevent double-disposal<br> <li> Updated finalizer to call Dispose(false) instead of directly calling <br>ReleaseBuffer()</ul>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/16804/files#diff-5ce7072dc525c523c3a724fea6d2c6b86111f746e4f993b3761bcb40163dee3a">+22/-14</a>&nbsp; </td>

</tr>
</table></td></tr></tbody></table>

</details>

___

### CODE REVIEW

**Comment by Piedone** [comment]
Thank you!

**Comment by nvborisenko** [comment]
@Piedone you can test it when nightly package (GitHub) will be released. Interesting whether it is proper fix.

**Comment by Piedone** [comment]
I'll check, yep.

File: dotnet/src/webdriver/BiDi/WebSocketTransport.cs [hunk 1]
```diff
@@ -28,12 +28,12 @@
...
 namespace OpenQA.Selenium.BiDi;
 
-class WebSocketTransport(Uri _uri) : ITransport, IDisposable
+sealed class WebSocketTransport(Uri _uri) : ITransport, IDisposable
 {
     private readonly static ILogger _logger = Internal.Logging.Log.GetLogger<WebSocketTransport>();
 
     private readonly ClientWebSocket _webSocket = new();
-    private readonly byte[] _receiveBuffer = ArrayPool<byte>.Shared.Rent(1024 * 8);
+    private byte[] _receiveBuffer = ArrayPool<byte>.Shared.Rent(1024 * 8);
```
Comment (nvborisenko) [inline dotnet/src/webdriver/BiDi/WebSocketTransport.cs:36]: @RenderMichael @YevgeniyShunevych what if we rent this buffer in the method, and return immediately? At least in this way we can remove finalizer, which brings more complexity.
