### PR TITLE
[grid] Fix race condition and improve logging in LocalSessionMap

### LINKED ISSUE #15347: [🐛 Bug]: Facing "Unable to find session with id" errors during initial executions of the test in the Selenium grid
### What happened?

Hi team! I've been debugging a probable issue with my selenium grid setup. A couple of seconds/minutes into my tests I face a lot of "Unable to find session with ID" exceptions and a large chunk of my test suite fails. The behaviour looks similar to the comment mentioned [here](https://github.com/SeleniumHQ/selenium/issues/14322#issuecomment-2265235273) just that in my case, since the grid is dynamic is could be an event where the node is initialized.

The configurations that I'm using for the hub:
```
      - env:
        - name: SE_ENABLE_TRACING
          value: "true"
        - name: SE_OPTS
          value: --log-level FINE
        - name: SE_NODE_SESSION_TIMEOUT
          value: "1800"
```

Image
Image
Image

Any pointers to debug this issue further would help. 

### How can we reproduce the issue?

```shell
The framework that is in use is a variant of the code present here (with the latest selenium version and JDK 17 as a requirement) : https://github.com/rookieInTraining/selenium-testng-boilerplate/tree/master
```

### Relevant log output

```shell
Unable to find session with ID: 7a6e3f0073bd7b9f385a5aa2da3d5521 Build info: version: '4.28.1', revision: '73f5ad48a2' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.58+', java.version: '17.0.13' Driver info: driver.version: unknown Build info: version: '4.28.0', revision: 'ac342546e9' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.14.0-362.24.2.el9_3.x86_64', java.version: '17.0.9' Driver info: org.openqa.selenium.remote.RemoteWebDriver Command: [7a6e3f0073bd7b9f385a5aa2da3d5521, get {url=https://space-prod0-automation.sprinklr.com//workforce-planner-app/home}] Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 132.0.6834.159, chrome: {chromedriverVersion: 132.0.6834.159 (2d77d3fc445..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:42597}, goog:loggingPrefs: {browser: ALL}, networkConnectionEnabled: false, pageLoadStrategy: none, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: wss://qa6-selenium-grid-car..., se:cdpVersion: 132.0.6834.159, se:containerName: care-chrome-node-579655886b..., se:name: workforce-management/smoke-..., se:noVncPort: 7900, se:vnc: wss://qa6-selenium-grid-car..., se:vncEnabled: true, se:vncLocalAddress: ws://10.102.35.210:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true} Session ID: 7a6e3f0073bd7b9f385a5aa2da3d5521
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:53)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:313)
com.spr.tests.workforcemanagement.ShiftActivityTest.goToActivities(ShiftActivityTest.java:20)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:568)
org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)
org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base/java.lang.Thread.run(Thread.java:842)
```

### Operating System

Linux (Docker)

### Selenium version

4.28.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

132.0.6834.159

### Are you using Selenium Grid?

4.28.1

### PR DESCRIPTION
**Pull request by VietND96**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Motivation and Context
Reproduce environment:
- Grid runs in containers, where multiple Nodes continuously attach/detach from the Hub. With a combination config of `SE_NODE_MAX_SESSIONS` > 1 and `SE_DRAIN_AFTER_SESSION_COUNT` > 1
- When `SE_DRAIN_AFTER_SESSION_COUNT`, the same container spawns up again with the same IP assigned, which results in a situation of `NodeRestartedEvent`
- Exception trace as below
> tests-1  | Build info: version: '4.35.0-SNAPSHOT', revision: 'Unknown'
tests-1  | System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.14-linuxkit', java.version: '21.0.8'
tests-1  | Driver info: driver.version: unknown
tests-1  |      at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:122)
tests-1  |      at org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)
tests-1  |      at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:225)
tests-1  |      at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:253)

Fixed race conditions in LocalSessionMap during concurrent node events by implementing thread-safe session management with read-write locks and defensive event handling.

**Race Condition Fix**
- Problem: Concurrent `NodeRemovedEvent` and `NodeRestartedEvent` during node shutdowns could cause thread safety issues when multiple events tried to remove the same sessions simultaneously.

- Solution:
  + Added ReentrantReadWriteLock to coordinate concurrent access to session storage
  + Read locks for session lookups (allowing concurrent reads)
  + Write locks for session modifications (exclusive access)
  + Batch removal with defensive checks prevents errors when sessions are already removed by concurrent events

**Improve logging of Local Session Map**
- Remove a single session message with the attached sessionId and nodeUri
- Remove all sessions by `NodeRemovedEvent` or `NodeRestartedEvent` message with the attached event class name triggered and nodeUri

> 06:16:10.933 INFO [GridModel.release] - Releasing slot for session id 32bc8a19-be78-4f11-8d80-39022e723160
06:16:10.934 INFO [LocalSessionMap.remove] - Deleted session from local Session Map, Id: 32bc8a19-be78-4f11-8d80-39022e723160, Node: http://172.18.0.10:5555
06:16:11.943 INFO [LocalSessionMap.batchRemoveByUri] - Event org.openqa.selenium.grid.data.NodeRemovedEvent triggered batch remove from local Session Map for Node http://172.18.0.10:5555
06:16:11.944 INFO [LocalSessionMap.batchRemoveByUri] - No sessions found to remove from local Session Map for Node http://172.18.0.10:5555
06:16:21.169 INFO [LocalSessionMap.remove] - Deleted session from local Session Map, Id: 96619a55bef67d0089d3184187479071, Node: http://172.18.0.5:5555

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Bug fix

___

### **Description**
- Replaced `NodeRemovedEvent` with `node.drain()` in `NodeServer` shutdown hook.

- Ensures proper session handling during node shutdown.

- Prevents unexpected session removal during server glitches or restarts.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>NodeServer.java</strong><dd><code>Updated NodeServer shutdown hook for graceful shutdown</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java

<li>Removed <code>NodeRemovedEvent</code> firing in the shutdown hook.<br> <li> Added <code>node.drain()</code> call to handle node draining during shutdown.<br> <li> Improved session management and shutdown behavior.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/15370/files#diff-6b57ab0a9dd897b266c9f06a46be2aa968b943059a7ed818ef049461b977d31e">+1/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

File: java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java [hunk 1]
```diff
@@ -77,8 +76,7 @@ public class NodeServer extends TemplateGridServerCommand {
   private final AtomicBoolean nodeRegistered = new AtomicBoolean(false);
   private Node node;
   private EventBus bus;
-  private final Thread shutdownHook =
-      new Thread(() -> bus.fire(new NodeRemovedEvent(node.getStatus())));
+  private final Thread shutdownHook = new Thread(() -> node.drain());
```
Comment (diemol) [inline java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java]: After checking the code briefly, I see that `NodeRemovedEvent` is processed in several places. I don't dislike shutting down the Node by draining it. We need to make sure we respect the current logic, which is to check where `NodeRemovedEvent` is used and adapt to it, or fire a `NodeRemovedEvent` when the Node drains.

Comment (VietND96) [reply java/src/org/openqa/selenium/grid/node/httpd/NodeServer.java]: I also checked, in `drain()` it will fire 2 events are `NodeDrainStarted` and `NodeDrainComplete`
Get back `NodeServer`, it also listen on event `NodeDrainComplete` for System.exit(0)
Do you think this event cycle is safe enough?

**Comment by joerg1985** [comment]
IMHO, this will not fix #15347, will report details later in the original issue.

**Comment by VietND96** [comment]
It might not fix 15347. However, sometimes I can reproduce with a strict condition, something like
There are multiple concurrent sessions, and new Nodes are continuously registered to Hub, each Node set `drain-after-session-count=3` (this might reproduce RestartedNode since container get restarted and back to Hub). The script steps in sequentially from create to quit().
Do you think something proceeded asynchronous? 

```
selenium.common.exceptions.InvalidSessionIdException: Message: Unable to find session with ID: 9d7b409b-b311-470a-b227-1944cd05ac73
Build info: version: '4.30.0-SNAPSHOT', revision: 'Unknown'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.12.5-linuxkit', java.version: '21.0.6'
Driver info: driver.version: unknown
Stacktrace:
org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 9d7b409b-b311-470a-b227-1944cd05ac73
Build info: version: '4.30.0-SNAPSHOT', revision: 'Unknown'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.12.5-linuxkit', java.version: '21.0.6'
Driver info: driver.version: unknown
        at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:117)
        at org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)
        at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:225)
        at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:253)
        at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:182)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:397)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.grid.router.Router.execute(Router.java:89)
        at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:49)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)


```

**Comment by joerg1985** [comment]
Without looking deeper into this i would assume the following **might** happen:

1. NodeRestartedEvent is raised
2. A new session is started
3. The NodeRestartedEvent.listener inside the LocalSessionMap i deleting the session, because it only checks the URL not the node id
4. The new session is accessed -> The LocalSessionMap has killed it just before.

Are you able to run a patched version of the Hub? If so, just remove the `NodeRestartedEvent.listener` inside the `LocalSessionMap` and see if you can still repoduce. If this is the case, the `NodeRestartedEvent.listener` inside all of the SessionMap's have to be reworked. But this is hard, as there are datebase changes involved ...

**Comment by joerg1985** [comment]
@VietND96 could you share the hub logs when this happens?
A NodeRestartedEvent is not rised at all in my local testcase with `--drain-after-session-count=1`

**Comment by VietND96** [comment]
Hub logs that I could collect for one case
```
2025-03-05 02:15:56 19:15:56.254 INFO [GridModel.release] - Releasing slot for session id e3ebecfb-7a2e-453a-9695-64593fff2c41
2025-03-05 02:15:56 19:15:56.255 INFO [LocalSessionMap.remove] - Deleted session from local Session Map, Id: e3ebecfb-7a2e-453a-9695-64593fff2c41
2025-03-05 02:15:56 19:15:56.255 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=fdd1232dd89e391cc004238dbf915833, spanId=752a65bf98e6d10a, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=null, attributes={service.name="selenium-hub", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.46.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=local_sessionmap.remove, kind=INTERNAL, startEpochNanos=1741115756254999846, endEpochNanos=1741115756255042763, attributes=AttributesMap{data={session.id=e3ebecfb-7a2e-453a-9695-64593fff2c41}, capacity=128, totalAddedValues=1}, totalAttributeCount=1, events=[ImmutableEventData{name=Deleted session from local Session Map, attributes={logger="org.openqa.selenium.grid.sessionmap.local.LocalSessionMap", session.id="e3ebecfb-7a2e-453a-9695-64593fff2c41"}, epochNanos=1741115756255010138, totalAttributeCount=2}], totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
2025-03-05 02:15:56 19:15:56.255 DEBUG [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "fdd1232dd89e391cc004238dbf915833","eventTime": 1741115756255010138,"eventName": "Deleted session from local Session Map","attributes": {"logger": "org.openqa.selenium.grid.sessionmap.local.LocalSessionMap","session.id": "e3ebecfb-7a2e-453a-9695-64593fff2c41"}}
...
2025-03-05 02:15:58 19:15:58.222 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
2025-03-05 02:15:58 DELETE /session/e3ebecfb-7a2e-453a-9695-64593fff2c41 HTTP/1.1
2025-03-05 02:15:58 Host: selenium-hub:4444
2025-03-05 02:15:58 Accept-Encoding: identity
2025-03-05 02:15:58 Accept: application/json
2025-03-05 02:15:58 Content-Type: application/json;charset=UTF-8
2025-03-05 02:15:58 User-Agent: selenium/4.29.0 (python linux)
2025-03-05 02:15:58 Connection: keep-alive
2025-03-05 02:15:58 19:15:58.222 DEBUG [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
2025-03-05 02:15:58 DELETE /session/e3ebecfb-7a2e-453a-9695-64593fff2c41 HTTP/1.1
2025-03-05 02:15:58 Host: selenium-hub:4444
2025-03-05 02:15:58 Accept-Encoding: identity
2025-03-05 02:15:58 Accept: application/json
2025-03-05 02:15:58 Content-Type: application/json;charset=UTF-8
2025-03-05 02:15:58 User-Agent: selenium/4.29.0 (python linux)
2025-03-05 02:15:58 Connection: keep-alive
2025-03-05 02:15:58 19:15:58.222 DEBUG [RequestConverter.channelRead0] - Incoming message: EmptyLastHttpContent
2025-03-05 02:15:58 19:15:58.222 DEBUG [RequestConverter.channelRead0] - End of http request: EmptyLastHttpContent
2025-03-05 02:15:58 19:15:58.223 DEBUG [HttpTracing.inject] - Injecting (DELETE) /session/e3ebecfb-7a2e-453a-9695-64593fff2c41 into OpenTelemetrySpan{traceId=0134c9a59ca7a43d7046b1b4bf408228,spanId=ea557e2f97942e5a} at org.openqa.selenium.grid.router.HandleSession:180
```
At between, you can see gaps 2 seconds, that is the wait time (by time.sleep in python) before calling `driver.quit()`
I see this will happen when using `drain-after-session-count`, LocalSessionMap will remove the session earlier than client call `driver.quit()` by the event NodeDrain.
Both GridModel and LocalSessionMap proceed the event `SessionClosedEvent`.

**Comment by joerg1985** [comment]
Could you share more of the logs, it is allways good to see what happened some time before and concurrently by other sessions.

**Comment by VietND96** [comment]
I attched full logs for id e33534f26859916b894c37fcb5da30df 
[e33534f26859916b894c37fcb5da30df.txt](https://github.com/user-attachments/files/19077774/e33534f26859916b894c37fcb5da30df.txt)
I also shared my scripts to reproduce the issue https://github.com/NDViet/selenium-grid-stress-test (it is nice if you are using macOS or Ubuntu to run it).

**Comment by VietND96** [comment]
@joerg1985, do you think currentSessions.cleanUp() in `drain()` is correct?
https://github.com/SeleniumHQ/selenium/blob/f779ad0c18c36d64a8a16b9d0d97fb69624e7c4a/java/src/org/openqa/selenium/grid/node/local/LocalNode.java#L1018-L1023
I think Node drain behavior should update Node status to DRAINING but still waiting for sessions to be completed, session only stops on demand (client call `quit()`), or session gets timed out.

**Comment by joerg1985** [comment]
> @joerg1985, do you think currentSessions.cleanUp() in drain() is correct?

Yes, It should only perform allready outstanding maintenance operations.
But i think there is no guarantee all outstanding calls to the removal listener are performed.

When reading the caffeine issues, there are alot of 'there is no guarantee for this and that' statements.

**Comment by VietND96** [comment]
Ignore qodo review, since  IndexedSessionMap is a custom ConcurrentMap implementation that maintains dual indexing for efficient session management in Grid:
Primary Index: SessionId → Session mapping for direct session lookup
Secondary Index: URI → Set<SessionId> mapping for node-based operations

Key Benefits & Use Cases
- Performance Optimization:
  - Fast session lookup: O(1) access by SessionId via primary map
  - Efficient node operations: O(1) lookup of all sessions on a specific node URI
  - Batch operations: Optimized removal of multiple sessions from the same node

- Grid Event Handling:
  - NodeRemovedEvent: Quickly find and remove all sessions from a removed node
  - NodeRestartedEvent: Efficiently clean up sessions from a restarted node
  - Session routing: Fast determination of which node hosts a specific session
