### PR TITLE
Loosen WebElementCondition instance checks

### LINKED ISSUE #5560: WebElementCondition not instanceof Condition
## Meta -
OS:  
OSX 10.13.3

Selenium Version:  
selenium-webdriver@4.0.0-alpha.1

Browser:  
Chrome

Browser Version:  
Version 64.0.3282.186 (Official Build) (64-bit)

## Expected Behavior -
`driver.wait()` should accept a WebElementCondition, i.e. `driver.wait(until.elementLocated(By.css(selector)))`

## Actual Behavior -
the above example throws the error `TypeError: Wait condition must be a promise-like object, function, or a Condition object`

## Steps to reproduce -
`driver.wait(until.elementLocated(By.css(selector)))`

This is some serious JavaScript weirdness:
`Object.getPrototypeOf(condition) ===  WebElementCondition {}`
yet `condition instanceof WebElementCondition === false`
weird, right?

I was able to get the case to pass by adding `condition.constructor.name === 'WebElementCondition'` to `if (condition instanceof Condition)` in the WebDriver's wait function.

### PR DESCRIPTION
**Pull request by afsmith92**
Update WebElementCondition and Condition with custom
static hasInstance methods so that `instanceof` checks
are more lenient and don't cause issues with Babel.

Fixes #5560

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

File: javascript/node/selenium-webdriver/lib/webdriver.js [hunk 1]
```diff
@@ -71,6 +71,19 @@ class Condition {
   description() {
     return this.description_;
   }
+
+  /**
+   * Allows for lenient instanceof checks
+   * @param {!(IThenable<T>|
+   *           Condition<T>|
+   *           function(!WebDriver): T)} condition - the condition instance
+   * @returns {*|boolean}
```
Comment (jleyba) [inline javascript/node/selenium-webdriver/lib/webdriver.js]: `@return {boolean}`

File: javascript/node/selenium-webdriver/lib/webdriver.js [hunk 2]
```diff
@@ -71,6 +71,19 @@ class Condition {
...
+   */
+  static [Symbol.hasInstance](condition) {
+    return condition
```
Comment (jleyba) [inline javascript/node/selenium-webdriver/lib/webdriver.js]: `return !!condition`

File: javascript/node/selenium-webdriver/lib/webdriver.js [hunk 3]
```diff
@@ -90,6 +103,19 @@ class WebElementCondition extends Condition {
...
   }
+
+  /**
+   * Allows for lenient instanceof checks
+   * @param {!(IThenable<T>|
+   *           Condition<T>|
+   *           function(!WebDriver): T)} condition - the condition instance
+   * @returns {*|boolean}
+   */
+  static [Symbol.hasInstance](condition) {
```
Comment (jleyba) [inline javascript/node/selenium-webdriver/lib/webdriver.js]: no need to define this a second time, it will be inherited from `Condition`

File: javascript/node/selenium-webdriver/lib/webdriver.js (hunk 2 above)
Comment (jleyba) [reply javascript/node/selenium-webdriver/lib/webdriver.js]: Actually, I'd probably be a little stricter:

`return !!condition && typeof condition === 'object'`

(plus the next two lines)

**Comment by barancev** [comment]
I've reverted this change by commit 61583115b8f360bafba302d0a3beb3eb8ab373f4 because it broke `x instanceof WebElementCondition` check that returns true even if `x` is an instance of the `Condition` class (a base class for `WebElementCondition`). All waits that return a boolean value or a string are affected.

The issue will be reopened too.
