### PR TITLE
[dotnet] [bidi] Fix events subscription possibilities

### LINKED ISSUE #16582: [🚀 Feature]: [dotnet] [bidi] Global subscription doesn't allow `context/UserContext`
### Description

```csharp
bidi.Network.OnBeforeRequestSent(...)
```

There is not support to specify `contexts`/`userContexts`.

https://w3c.github.io/webdriver-bidi/#cddl-type-sessionsubscriptionrequest

Previously we agreed low-level api should mimic spec, that's it.

### Have you considered any alternatives or workarounds?

_No response_

### PR DESCRIPTION
**Pull request by nvborisenko**
### 🔗 Related Issues

I am not able to scope global events to `context`. Fixes https://github.com/SeleniumHQ/selenium/issues/16582

```csharp
bidi.Network.OnBeforeRequestAsync(new SubscriptionOptions { Contexts = [ ...??? ]});
```

It is design issue. When I am in bidi global context, then I should be able to specify `Contexts` or `UserContexts`.

### 💥 What does this PR do?

Now it is clear. When I use `bidi` global object, then I can do everything as specification describes. But if I am in `browsingContext`, then events are automatically scoped to this BrowsingContext (implicitly provided when subscribing).

### 🔄 Types of changes

- New feature (non-breaking change which adds functionality *and tests!*)

### CODE REVIEW

**Comment by nvborisenko** [comment]
@RenderMichael @YevgeniyShunevych now public API for end-user looks clear, and provides all required capabilities.

But internally the implementation blows my mind. Can we optimize it somehow to avoid types messing?

File: dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContextNetworkModule.cs [hunk 1]
```diff
@@ -17,9 +17,9 @@
 // under the License.
 // </copyright>
 
-using System.Threading.Tasks;
-using System;
 using OpenQA.Selenium.BiDi.Network;
+using System;
```
Comment (RenderMichael) [inline dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContextNetworkModule.cs:21]: There are some conventions on the `using` statements which say it should be in alphabetical order; there are others that say alphabetical *except* ones that start with `System`.

We should pick one and set it in the editorconfig, to avoid going back and forth forever.

File: dotnet/src/webdriver/BiDi/Subscription.cs [hunk 2]
```diff
@@ -51,15 +51,23 @@ public async ValueTask DisposeAsync()
...
-    {
-        Timeout = options?.Timeout;
-    }
+    public TimeSpan? Timeout { get; set; }
+}
 
-    public IEnumerable<BrowsingContext.BrowsingContext>? Contexts { get; set; }
+internal static class ContextSubscriptionOptionsExtensions
+{
+    public static SubscriptionOptions WithContext(this ContextSubscriptionOptions? options, BrowsingContext.BrowsingContext context) => new()
```
Comment (RenderMichael) [inline dotnet/src/webdriver/BiDi/Subscription.cs:70]: It is strange to have an extension method with a reciever that can be `null`. Do we ever have a null `ContextSubscriptionOptions options`?

**Review by RenderMichael — APPROVED** [review]
I like this approach.

File: dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContextNetworkModule.cs (hunk 1 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContextNetworkModule.cs:21]: Current "convention" is alphabetical. I tried to apply editorconfig from dotnet/runtime: https://github.com/SeleniumHQ/selenium/pull/16420 - it is big change. Will be glad to return to this discussion later.

File: dotnet/src/webdriver/BiDi/Subscription.cs (hunk 2 above)
Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Subscription.cs:70]: Yes, usually user may not provide non-null options to subscribe.

Comment (nvborisenko) [reply dotnet/src/webdriver/BiDi/Subscription.cs:70]: Left a comment for clarity.

File: dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContextNetworkModule.cs (hunk 1 above)
Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/BrowsingContext/BrowsingContextNetworkModule.cs:21]: Good idea, separate discussion. Just bringing it up because of the code change.

File: dotnet/src/webdriver/BiDi/Subscription.cs (hunk 2 above)
Comment (RenderMichael) [reply dotnet/src/webdriver/BiDi/Subscription.cs:70]: Since this method is not public API, it is not a big deal.

**Review by RenderMichael — APPROVED** [review]
